apache/incubator-kie-kogito-docs

.github/workflows/npm-publish-pages.yml, README.adoc
This Github action is run on every pull request merged into the main branch. This action will upload the build artifacts to gh-pages branch. Github pages will render this content.
=> KOGITO-7232: Push GH action on main to deploy on GH pages

.github/workflows/npm-publish-pages.yml
- Disabled npm cache due to GH action bug 
https://github.com/bahmutov/npm-install/issues/80
=> KOGITO-7232: Push kogito-docs build to GH Pages

serverlessworkflow/modules/ROOT/pages/security/authention-support-for-openapi-services.adoc
Add a new section in the guide to describe the feature provided by KOGITO-6458:
- new property "quarkus.openapi-generator.codegen.default.security.scheme"
- create security bindings if property value matches any of the defined securityScheme definitions
JIRA: https://issues.redhat.com/browse/KOGITO-6458
Related commit: https://github.com/quarkiverse/quarkus-openapi-generator/commit/ccacff5e212aa6c615a44dfec69958ca5e248478
=> KOGITO-6458: Update the guide to describe new feature of default security definition

serverlessworkflow/modules/ROOT/pages/core/understanding-jq-expressions.adoc
This PR fixes a broken link in serverlessworkflow/modules/ROOT/pages/core/understanding-jq-expressions.adoc
=> Fixed broken link

serverlessworkflow/modules/ROOT/nav.adoc, serverlessworkflow/modules/ROOT/pages/testing-and-troubleshooting/mocking-opnapi-services-with-wiremock.adoc
**JIRA:** https://issues.redhat.com/browse/KOGITO-7313
------------
=> KOGITO-7313 Added "Mocking OpenAPI services with WireMock" guide

serverlessworkflow/modules/ROOT/nav.adoc, serverlessworkflow/modules/ROOT/pages/testing-and-troubleshooting/mocking-http-cloudevents-with-wiremock.adoc
**JIRA:**https://issues.redhat.com/browse/KOGITO-7312
**Description:**Patch PR for KOGITO-7311 with doc improvements in Mocking HTTP CloudEvents sink with Wiremock guide
https://github.com/kiegroup/kogito-docs/pull/55/
=> KOGITO-7312: Patch PR for KOGITO-7311 with doc improvements in Mocking HTTP CloudEvents sink with Wiremock guide

serverlessworkflow/modules/ROOT/pages/core/understanding-jq-expressions.adoc
**JIRA:**
https://issues.redhat.com/projects/KOGITO/issues/KOGITO-7664
=> KOGITO-7664 Fix wrong name of property in text (`substractvalue` -> `subtractValue`)

antora/supplemental-ui/css/custom.css
**JIRA:** https://issues.redhat.com/browse/KOGITO-7693
When table data cell has long words, the table width increases to cover the longer word.
=> KOGITO-7693: Fixed table data overflow for large word

antora-playbook.yml, serverlessworkflow/modules/ROOT/pages/eventing/handling-events-on-workflows.adoc
Depends on:
- 1.24.x => https://github.com/kiegroup/kogito-docs/pull/118
- 1.25.x => https://github.com/kiegroup/kogito-docs/pull/121
=> Added 1.24.x and 1.25.x branches for generation

serverlessworkflow/antora.yml, serverlessworkflow/modules/ROOT/pages/cloud/deploying-on-minikube.adoc, serverlessworkflow/modules/ROOT/pages/getting-started/create-your-first-workflow-service.adoc, serverlessworkflow/modules/ROOT/pages/tooling/kn-plugin-workflow-overview.adoc
**JIRA:** https://issues.redhat.com/browse/KOGITO-7694
* Fixed `kn` commands in the Getting Started guide
* Added quarkus and kogito versions to `kn workflow create` command
* Created a dedicated section for building the project after the "Creating a workflow" section
* Added `dev.local` as repository to `kn-plugin-workflow-overview.adoc` - @ljmotta can you review please?
* Fixed broken link in deploying-on-minikube.adoc
=> KOGITO-7694 Fixed kn commands in create-your-first-workflow-service.adoc

serverlessworkflow/antora.yml, serverlessworkflow/modules/ROOT/pages/_common-content/downstream-project-setup-instructions.adoc, serverlessworkflow/modules/ROOT/pages/getting-started/create-your-first-workflow-service.adoc, serverlessworkflow/modules/ROOT/pages/tooling/kn-plugin-workflow-overview.adoc
**JIRA:** https://issues.redhat.com/browse/KOGITO-7767
**Description:** Include our early access maven repo to the settings.xml, remove unused var, and the `-P` flag from quarkus CLI command.-P
=> [KOGITO-7767] - Fix Maven instructions to add earlyaccess config

serverlessworkflow/antora.yml, serverlessworkflow/modules/ROOT/pages/getting-started/create-your-first-workflow-service.adoc, serverlessworkflow/modules/ROOT/pages/tooling/kn-plugin-workflow-overview.adoc
This PR updates the kn_cli_version to 0.21.3 (release in progress), and updates the Building from source section.
=> Fix Workflow plug-in version and Building from source section

serverlessworkflow/modules/ROOT/nav.adoc, serverlessworkflow/modules/ROOT/pages/core/defining-an-input-schema-for-workflows.adoc, serverlessworkflow/modules/ROOT/pages/index.adoc
**JIRA:** https://issues.redhat.com/browse/KOGITO-7260
**Description:** Patch PR for KOGITO-7250 with doc improvements in input schema guide
https://github.com/kiegroup/kogito-docs/pull/151
<details>
<summary>
</summary>
*NOTE: You can still add label after the merge and it …
=> KOGITO-7260: Patch PR for KOGITO-7250 with doc improvements in input schema guide

.ci/jenkins/Jenkinsfile.init, .ci/jenkins/dsl/jobs.groovy
chery-pick: https://github.com/kiegroup/kogito-docs/pull/122
<details>
<summary>
</summary>
</details>
=> [1.26.x] KOGITO-7715 Pipelines: setup init job (#122)

serverlessworkflow/modules/ROOT/pages/service-orchestration/orchestration-of-openapi-based-services.adoc
**JIRA:** https://issues.redhat.com/projects/KOGITO/issues/KOGITO-7855
<details>
<summary>
</summary>
</details>
=> KOGITO-7855 Fix colision of `:quarkus_config_url:`

CONTRIBUTING.md, serverlessworkflow/modules/ROOT/nav.adoc, serverlessworkflow/modules/ROOT/pages/release_notes.adoc
**JIRA:**
<details>
<summary>
</summary>
</details>
=> Add Release notes for 1.26 and contrib guides

serverlessworkflow/modules/ROOT/nav.adoc, serverlessworkflow/modules/ROOT/pages/cloud/kubernetes-service-discovery.adoc, serverlessworkflow/modules/ROOT/pages/index.adoc
**JIRA:** https://issues.redhat.com/browse/KOGITO-7910
**Description:** Patch PR for Kubernetes service discovery guide with doc improvements
https://github.com/kiegroup/kogito-docs/pull/177
<details>
<summary>
</summary>
*NOTE: You can still add label after the merge and it …
=> KOGITO-7910: Patch PR for Kubernetes service discovery guide with doc improvements

serverlessworkflow/modules/ROOT/pages/eventing/consume-produce-events-with-knative-eventing.adoc
**JIRA:**
https://issues.redhat.com/browse/KOGITO-7944
<details>
<summary>
</summary>
</details>
=> KOGITO-7944 Fix `:knative_eventing_doc_url:` extra '/' and broken link

serverlessworkflow/modules/ROOT/pages/release_notes.adoc
Let the Release Notes in main be a template rather than an old version.
=> Templating release notes for snapshot versions

.github/workflows/cherry-pick.yml
Following merge and release of https://github.com/carloscastrojumo/github-cherry-pick-action/pull/10
=> GHA cherry-pick: Setting back correct action

.github/CODEOWNERS
Since @kaldesai will now help us while @hmanwani-rh is on PTO, I'm changing the approval chain to her.
=> Adding kaldesai as codeowner for docs

.ci/jenkins/Jenkinsfile.init-branch, .ci/jenkins/Jenkinsfile.post-release
https://issues.redhat.com/browse/KOGITO-8043
Related:
- https://github.com/kiegroup/kogito-pipelines/pull/634
- https://github.com/kiegroup/kogito-pipelines/pull/636
- https://github.com/kiegroup/drools/pull/4725
- https://github.com/kiegroup/kogito-runtimes/pull/2527
- https://github.com/kiegroup/kogito-apps/pull/1485
- https://github.com/kiegroup/kogito-examples/pull/1425
- https://github.com/kiegroup/kogito-images/pull/1344
- https://github.com/kiegroup/kogito-operator/pull/1295
- https://github.com/kiegroup/kogito-docs/pull/220
=> [1.28.x] KOGITO-8043 Jenkins node master -> built-in

serverlessworkflow/modules/ROOT/pages/service-orchestration/orchestration-of-grpc-services.adoc
**JIRA:** [KOGITO-7967](https://issues.redhat.com/browse/KOGITO-7967)
**Description:** I reviewed the content for the procedure to start the gRPC application in the guide. 
<details>
<summary>
How to set up automatic cherry-pick to another branch?
</summary>
*NOTE: You can still add label after the merge and it should still be …
=> Docs Patch PR for KOGITO-7967: Improve clarity of procedure to start gRPC application in the guide

serverlessworkflow/modules/ROOT/pages/getting-started/cncf-serverless-workflow-specification-support.adoc
**Description:** 
Updating the CNCF section with the icon for partial implementation of timeouts, the text was already updated in the guide PR.
<details>
<summary>
</summary>
</details>
=> Updating icon for timeout support in CNCF section

serverlessworkflow/modules/ROOT/pages/core/custom-functions-support.adoc
**JIRA:[KOGITO-8078](https://issues.redhat.com/browse/KOGITO-8078)**
**Description:** I reviewed the content for the **Custom function types** section and added my suggestions. Please take a look and reach out to me if you have any questions.
<details>
<summary>
</summary>
*NOTE: …
=> Docs Patch PR for KOGITO-8078: Document adding custom type through addon

serverlessworkflow/modules/ROOT/pages/cloud/build-workflow-image-with-quarkus-cli.adoc, serverlessworkflow/modules/ROOT/pages/cloud/deploying-on-minikube.adoc, serverlessworkflow/modules/ROOT/pages/core/timeouts-support.adoc, serverlessworkflow/modules/ROOT/pages/core/understanding-jq-expressions.adoc, serverlessworkflow/modules/ROOT/pages/core/working-with-parallelism.adoc, serverlessworkflow/modules/ROOT/pages/security/orchestrating-third-party-services-with-oauth2.adoc, serverlessworkflow/modules/ROOT/pages/service-orchestration/configuring-openapi-services-endpoints.adoc, serverlessworkflow/modules/ROOT/pages/service-orchestration/orchestration-of-grpc-services.adoc, serverlessworkflow/modules/ROOT/pages/testing-and-troubleshooting/basic-integration-tests-with-restassured.adoc, serverlessworkflow/modules/ROOT/pages/use-cases/orchestration-based-saga-pattern.adoc
**JIRA:** https://issues.redhat.com/browse/KOGITO-7975
Related PR: https://github.com/kiegroup/kogito-examples/pull/1446
<details>
<summary>
</summary>
</details>
=> KOGITO-7975 Removed workflowdata property from requests

.github/workflows/npm-publish-pages.yml
**JIRA:**https://issues.redhat.com/browse/KOGITO-8318
<details>
<summary>
</summary>
</details>
=> KOGITO-8318 Trigger Publish pages on release branches push

serverlessworkflow/antora.yml, serverlessworkflow/modules/ROOT/pages/eventing/consume-produce-events-with-knative-eventing.adoc
Adding more information to the guides, see:
- [Update Knative Eventing Serverless Workflow Guide to add Incoming HTTP configuration](https://issues.redhat.com/browse/KOGITO-8141)
- [Improve Knative Eventing doc by adding an example how to send and consume HTTP events](https://issues.redhat.com/browse/KOGITO-8309)
**JIRA:**
<details>
<summary>
</summary>
For example, if a backport to branch `1.26.x` is needed, …
=> [KOGITO-8141][KOGITO-8309] - Enhancing Knative Eventing guide with info about local testing

serverlessworkflow/antora.yml, serverlessworkflow/modules/ROOT/nav.adoc, serverlessworkflow/modules/ROOT/pages/_common-content/camel-valid-responses.adoc, serverlessworkflow/modules/ROOT/pages/core/custom-functions-support.adoc, serverlessworkflow/modules/ROOT/pages/index.adoc, serverlessworkflow/modules/ROOT/pages/integrations/camel-routes-integration.adoc
**JIRA:** https://issues.redhat.com/browse/KOGITO-8353
**Description:** In this PR, we introduce a new guide exemplifying how to use the new Camel Route custom function for Serverless Workflow.
<details>
<summary>
</summary> …
=> [KOGITO-8353] Introduce Camel Routes integration guide

serverlessworkflow/modules/ROOT/pages/release_notes.adoc
**JIRA:** [KOGITO-7676](https://issues.redhat.com/browse/KOGITO-7676)
<details>
<summary>
</summary>
</details>
=> [1.32.x] KOGITO-7676: Added Flyway to release notes

serverlessworkflow/modules/ROOT/pages/release_notes.adoc
**JIRA:** https://issues.redhat.com/browse/KOGITO-8322
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific …
=> [1.33.x] KOGITO-8322: Added flyway impl for Data-Index on Oracle.

serverlessworkflow/modules/ROOT/pages/getting-started/create-your-first-workflow-service.adoc
There's no apparent reason to add this dependency to the project. Users might use the Cloud Guides to build/generate the application image instead of adding the extension in the Getting Started.
=> Remove unnecessary quarkus-container-jib extension

serverlessworkflow/modules/ROOT/pages/core/timeouts-support.adoc
This should be the last one from my "catching up with what happened" work. :slightly_smiling_face: 
The overlooked comment is [this](https://github.com/kiegroup/kogito-docs/pull/290/files#r1090721318) one.
<details>
<summary>
</summary> …
=> Fix overlooked comment from Job Service docs PR + other fixes

serverlessworkflow/modules/ROOT/pages/cloud/kubernetes-service-discovery.adoc
Reverted changes regarding `kogito-addons-quarkus-kubernetes` dependency.
Commit that revert the dependencies to their original state: https://github.com/kiegroup/kogito-runtimes/pull/2711/commits/14a062431ee561316923f7643ae8821a57ee19d2
With that commit, the dependencies were reverted to their original state. That means `kogito-addons-quarkus-kubernetes` is now opt-out again as it used to be.
**JIRA:** https://issues.redhat.com/browse/KOGITO-8414
------------
<details>
<summary>
</summary>
In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., …
=> Reverted change in kubernetes-service-discovery.adoc

serverlessworkflow/modules/ROOT/pages/persistence/postgresql-flyway-migration.adoc
Small update to the guide highlights that Flyway won't upgrade the database automatically.
@akumar074 @cristianonicolai feel free to update this PR directly. This is just a reminder that we must update the guide and backport it.
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is …
=> Add a note to the db migration guide about default behavior

serverlessworkflow/modules/ROOT/pages/cloud/kubernetes-service-discovery.adoc
**JIRA:** https://issues.redhat.com/browse/KOGITO-8443
Related to: https://github.com/kiegroup/kogito-runtimes/pull/2924
----------
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or …
=> KOGITO-8443 Added note about simplified format for Knative service discovery

serverlessworkflow/modules/ROOT/pages/core/custom-functions-support.adoc
**JIRA:** https://issues.redhat.com/browse/KOGITO-8848
- https://github.com/kiegroup/kogito-runtimes/pull/2967
-------------
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a …
=> KOGITO-8848 Added note about CloudEvent ID to Knative Custom Function

serverlessworkflow/modules/ROOT/pages/cloud/quarkus/kubernetes-service-discovery.adoc, serverlessworkflow/modules/ROOT/pages/integrations/custom-functions-knative.adoc
Reverts kiegroup/kogito-docs#349
runtimes/examples PR are not in 1.39.x ...
=> Revert "[1.39.x] KOGITO-9144 Added information about how to enable service discovery"

serverlessworkflow/modules/ROOT/pages/cloud/operator/configuring-workflows.adoc, serverlessworkflow/modules/ROOT/pages/eventing/consume-produce-events-with-knative-eventing.adoc
**JIRA:** https://issues.redhat.com/browse/KOGITO-9210
See this comment: https://issues.redhat.com/browse/KOGITO-9210?focusedId=22340763&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-22340763
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a …
=> KOGITO-9210 Fixed `org.kie.kogito.addons.knative` properties.

serverlessworkflow/modules/ROOT/pages/cloud/quarkus/kubernetes-service-discovery.adoc
**JIRA:** https://issues.redhat.com/browse/KOGITO-9315
**Description:** Small update to the discovery guide to include the kogito kubernetes add-on additionally to the fabric8 one.
Depends on:
- https://github.com/kiegroup/kogito-runtimes/pull/3056
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is …
=> [KOGITO-9315] Updating docs to include Kogito Kubernetes Add-on to Discovery

CONTRIBUTING.md
Backport to main of contributing guidelines from #372.
<details>
<summary>
</summary>
Once the original pull request is …
=> Improve contributing guidelines for release notes

.ci/jenkins/Jenkinsfile.post-release
**JIRA:**
<details>
<summary>
</summary> …
=> CI: Fix set `operator_version` attribute

serverlessworkflow/modules/ROOT/pages/cloud/operator/install-serverless-operator.adoc
The new namespace and operator prefix is `sonataflow`. Therefore, the instructions are updated accordingly, and some of the outputs of the commands.
=> Update operator installation instructions to new prefix

serverlessworkflow/modules/ROOT/pages/cloud/operator/developing-workflows.adoc
Operator [v1.42](quay.io/kiegroup/kogito-serverless-operator:1.42) doesn't support the `specVersion` in SonataFlow CRD. Updating the example not to fail with:
```
Error from server (BadRequest): error when creating "example.yaml": SonataFlow in version "v1alpha08" cannot be handled as a SonataFlow: strict decoding error: unknown field "spec.flow.specVersion"
```
=> Remove specVersion property from example

serverlessworkflow/modules/ROOT/nav.adoc, serverlessworkflow/modules/ROOT/pages/cloud/index.adoc, serverlessworkflow/modules/ROOT/pages/cloud/operator/build-and-deploy-workflows.adoc, serverlessworkflow/modules/ROOT/pages/cloud/operator/developing-workflows.adoc, serverlessworkflow/modules/ROOT/pages/cloud/operator/migration-guide.adoc
**JIRA:**
https://issues.redhat.com/browse/KOGITO-9218
Follow up on the changes on:
- https://github.com/kiegroup/kogito-serverless-operator/pull/214
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally …
=> [KOGITO-9218] - Update SonataFlowPlatform struct

serverlessworkflow/modules/ROOT/pages/core/custom-functions-support.adoc
**JIRA:** https://issues.redhat.com/browse/KOGITO-8410
- https://github.com/kiegroup/kogito-runtimes/pull/3172
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release …
=> KOGITO-8410 Added documentation about GET requests to Knative Custom Functions

serverlessworkflow/modules/ROOT/pages/cloud/quarkus/kubernetes-service-discovery.adoc
**JIRA:** https://issues.redhat.com/browse/KOGITO-9145
- https://github.com/kiegroup/kogito-runtimes/pull/3179
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release …
=> KOGITO-9145 Added information about kogito-addons-quarkus-microprofile-config-service-catalog

serverlessworkflow/modules/ROOT/pages/cloud/operator/build-and-deploy-workflows.adoc
**JIRA:**
https://issues.redhat.com/browse/KOGITO-9184
This small update reflects the new feature added by the linked JIRA.
- https://github.com/kiegroup/kogito-serverless-operator/pull/246/
<details>
<summary>
</summary> …
=> [KOGITO-9184] Describing how to pass args and envs to the SonataFlow build process

serverlessworkflow/modules/ROOT/pages/cloud/quarkus/kubernetes-service-discovery.adoc
**JIRA:** https://issues.redhat.com/browse/KOGITO-9757
- https://github.com/kiegroup/kogito-runtimes/pull/3188
------
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific …
=> KOGITO-9757 Changed property expansion to use ${property_name}

.ci/jenkins/Jenkinsfile.post-release, .ci/jenkins/Jenkinsfile.setup-branch, .ci/jenkins/dsl/jobs.groovy, .ci/jenkins/dsl/test.sh, .github/pull_request_template.md, .github/workflows/jenkins-tests-PR.yml
- https://github.com/kiegroup/kogito-pipelines/pull/1078
- https://github.com/kiegroup/kogito-runtimes/pull/3223
- https://github.com/kiegroup/kogito-examples/pull/1806
- https://github.com/kiegroup/kogito-apps/pull/1877
- https://github.com/kiegroup/kogito-images/pull/1698
- https://github.com/kiegroup/kogito-operator/pull/1528
- https://github.com/kiegroup/kogito-serverless-operator/pull/250
- https://github.com/kiegroup/kogito-docs/pull/497
- https://github.com/kiegroup/drools/pull/5519
- https://github.com/kiegroup/drools-website/pull/269
- https://github.com/radtriste/kie-benchmarks/pull/1 (WARNING: on `radtriste`, not on `kiegroup !`)
- https://github.com/asf-transfer/optaplanner/pull/2968
- https://github.com/kiegroup/optaplanner-quickstarts/pull/601
=> Update `kiegroup` repository references to `apache`

.ci/jenkins/Jenkinsfile.post-release, .ci/jenkins/Jenkinsfile.setup-branch, .ci/jenkins/dsl/jobs.groovy, .ci/jenkins/dsl/test.sh, .github/pull_request_template.md, .github/workflows/jenkins-tests-PR.yml
apache/incubator-kie-kogito-pipelines#1090
apache/incubator-kie-kogito-runtimes#3233
apache/incubator-kie-kogito-apps#1882
apache/incubator-kie-kogito-examples#1810
apache/incubator-kie-kogito-images#1703
apache/incubator-kie-kogito-operator#1530
apache/incubator-kie-kogito-serverless-operator#257
apache/incubator-kie-kogito-docs#504
apache/incubator-kie-docs#4529
apache/incubator-kie-drools#5531
apache/incubator-kie-optaplanner#2985
apache/incubator-kie-optaplanner-quickstarts#607
apache/incubator-kie-benchmarks#262
=> kie-issues#574 Initial ASF Jenkins CI Setup

serverlessworkflow/modules/ROOT/nav.adoc, serverlessworkflow/modules/ROOT/pages/cloud/operator/known-issues.adoc
Small update tom reflect the current context/backlog for 1.44+ version.
=> :pencil: Update Operator Roadmap for 1.44+

serverlessworkflow/modules/ROOT/nav.adoc, serverlessworkflow/modules/ROOT/pages/service-orchestration/configuring-openapi-services-endpoints.adoc, serverlessworkflow/modules/ROOT/pages/service-orchestration/orchestration-of-openapi-based-services.adoc, serverlessworkflow/modules/ROOT/pages/service-orchestration/troubleshooting.adoc
**JIRA:**
https://issues.redhat.com/browse/KOGITO-9838
In this PR, we complement the work in KOGITO-9838 by adding a quick troubleshooting guide for remote service invocations. We should keep updating this guide with more information.
https://github.com/apache/incubator-kie-kogito-runtimes/pull/3238
<details>
<summary>
</summary>
> **NOTE**: …
=> [KOGITO-9838] Add a troubleshooting guide for remote service invocations

serverlessworkflow/modules/ROOT/nav.adoc, serverlessworkflow/modules/ROOT/pages/cloud/index.adoc, serverlessworkflow/modules/ROOT/pages/cloud/operator/customize-podspec.adoc, serverlessworkflow/modules/ROOT/pages/cloud/operator/known-issues.adoc
**JIRA:**
https://issues.redhat.com/browse/KOGITO-9265
In this PR, we add a new guide to explain the new feature able to customize PodSpec in SonataFlow CR.
Depends on:
- https://github.com/apache/incubator-kie-kogito-serverless-operator/pull/255
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change …
=> [KOGITO-9265] Add PodSpec customization guide

serverlessworkflow/modules/ROOT/pages/cloud/operator/developing-workflows.adoc
**JIRA:** No Jira issue
As reported in Issue #468, in [Deploying a New Workflow](https://sonataflow.org/serverlessworkflow/main/cloud/operator/developing-workflows.html#_deploying_a_new_workflow) section, there are two broken links.
> Deploying the greeting Workflow example
>
> `kubectl apply -f https://raw.githubusercontent.com/kiegroup/kogito-serverless-operator/main/test/testdata/sw.kogito_v1alpha08_sonataflow_devmode.yaml -n <your_namespace>`
And
> For example using VSCode, there are the commands needed:
>
> curl -S https://raw.githubusercontent.com/kiegroup/kogito-serverless-operator/main/config/samples/sw.kogito_v1alpha08_sonataflow_devmode.yaml > workflow_devmode.yaml
>code workflow_devmode.yaml
> kubectl apply -f workflow_devmode.yaml -n <your_namespace>
Please …
=> Update broken links in developing workflows guide

serverlessworkflow/modules/ROOT/pages/core/custom-functions-support.adoc
**JIRA:** N/A
This PR adds a link to the Kubernetes Service Discovery page when using Knative custom function
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. …
=> Add reference to Kubernetes Service Discovery for Knative function

.asf.yaml, .github/workflows/sw-docs-pr.yml, antora-playbook.yml, package.json, serverlessworkflow/antora.yml
In this PR, we fix all the old repo references when building the documentation website. Also added the `.asf.yaml` file to follow the best practices and configure the repository accordingly. See https://cwiki.apache.org/confluence/display/INFRA/Git+-+.asf.yaml+features#Git.asf.yamlfeatures-GitHubPages
=> Fix kiegroup references and add github pages settings

.ci/jenkins/Jenkinsfile.post-release, .ci/jenkins/Jenkinsfile.setup-branch, .ci/jenkins/dsl/jobs.groovy, .ci/jenkins/dsl/test.sh, .github/workflows/jenkins-tests-PR.yml, .github/workflows/npm-publish-pages.yml, .github/workflows/pr-backporting.yml, .github/workflows/sw-docs-pr.yml, CONTRIBUTING.md, NOTICE, README.adoc, antora-playbook-author.yml, antora-playbook.yml, antora/supplemental-ui/js/tabsBehavior.js, antora/supplemental-ui/partials/header-content.hbs, scripts/copy-latest.py, serverlessworkflow/antora.yml, serverlessworkflow/modules/ROOT/nav.adoc, serverlessworkflow/modules/ROOT/pages/cloud/operator/build-and-deploy-workflows.adoc, serverlessworkflow/modules/ROOT/pages/cloud/operator/developing-workflows.adoc, serverlessworkflow/modules/ROOT/pages/cloud/operator/install-serverless-operator.adoc, serverlessworkflow/modules/ROOT/pages/cloud/quarkus/build-workflow-image-with-quarkus-cli.adoc, serverlessworkflow/modules/ROOT/pages/job-services/core-concepts.adoc, serverlessworkflow/modules/ROOT/pages/persistence/persistence-with-postgresql.adoc, serverlessworkflow/modules/ROOT/pages/security/orchestrating-third-party-services-with-oauth2.adoc, serverlessworkflow/modules/ROOT/pages/testing-and-troubleshooting/basic-integration-tests-with-restassured.adoc, serverlessworkflow/modules/ROOT/pages/tooling/serverless-logic-web-tools/serverless-logic-web-tools-deploy-projects.adoc, serverlessworkflow/modules/ROOT/pages/use-cases/timeout-showcase-example.adoc
**JIRA:**
Closes: https://github.com/apache/incubator-kie-issues/issues/471
Please notice I am not adding headers to all `.adoc` files, because on apache pages is written it is not needed for code snippet that is included into some parent, that has header https://www.apache.org/legal/src-headers.html#faq-exceptions
This PR also replaces github **kiegroup** references to github **apache** references
<details>
<summary>
</summary>
In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., …
=> incubator-kie-issues#471: Add apache headers license into files

.ci/jenkins/Jenkinsfile.post-release, .ci/jenkins/Jenkinsfile.setup-branch
apache/incubator-kie-issues#667
Fixing cleanup and settings.xml pipeline configuration to work correctly in ASF Jenkins.
* Deferred wipeout was causing issues when invoked in early stages
* Docker cleanup can't be done since the overall build is in docker container that uses the docker.sock from the host - it would attempt to erase itself.
* withSettingsXmlId shared library method does imply usage of a prohibited groovy method, thus replacing with explicit configFileProvider and passing as withSettingsXmlFile goes around that part of code. 
Complete list:
apache/incubator-kie-kogito-pipelines#1113
apache/incubator-kie-kogito-runtimes#3272
apache/incubator-kie-kogito-apps#1909
apache/incubator-kie-kogito-examples#1820
apache/incubator-kie-drools#5572
apache/incubator-kie-optaplanner#3010 …
=> kie-issues#667: fix cleanup and settingsXml handling

serverlessworkflow/modules/ROOT/pages/cloud/operator/customize-podspec.adoc
Signed-off-by: Roy Golan <rgolan@redhat.com>
=> Fix memory unit from "mi:" to "Mi"

serverlessworkflow/modules/ROOT/pages/core/custom-functions-support.adoc
Tracking JIRA: https://issues.redhat.com/browse/SRVLOGIC-83
I am currently using and referring to this link: [About OpenShift Serverless Logic](https://openshift-knative.github.io/docs/docs/latest/serverless-logic/about.html)
Is this the correct resource I am referring to?
=> SRVLOGIC-83: Remove "Kogito" name from Serverless Logic documents

serverlessworkflow/antora.yml, serverlessworkflow/modules/ROOT/pages/core/understanding-jq-expressions.adoc
https://issues.redhat.com/browse/KOGITO-7257
=> [KOGITO-7257] Documenting workflow metainfo

.github/CODEOWNERS
@MarianMacik is no more a contributor to this project, unfortunately. :( 
So we will remove him from `CODEOWNERS` to avoid spam in his notification inbox. :)
=> [NO-ISSUE] Remove Marian from CODEOWNERS

serverlessworkflow/modules/ROOT/pages/core/custom-functions-support.adoc
Closes/Fixes/Resolves https://issues.redhat.com/browse/KOGITO-7413
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a …
=> [KOGITO-7413] Adding custom rest

serverlessworkflow/modules/ROOT/pages/core/understanding-jq-expressions.adoc
Updated the doc once the example has been updated. 
See https://github.com/apache/incubator-kie-kogito-examples/issues/1868
=> Updating prevActionResult with example reference

.github/workflows/pr-preview-build.yml, .github/workflows/pr-preview-publish.yml
Small PR to verify if the preview actions are working and fixing it.
Relates to #539 
<details>
<summary>
</summary> …
=> Remove push action from build action / verify preview run

serverlessworkflow/modules/ROOT/pages/cloud/index.adoc, serverlessworkflow/modules/ROOT/pages/cloud/operator/enabling-jobs-service.adoc, serverlessworkflow/modules/ROOT/pages/cloud/operator/install-serverless-operator.adoc
Extends the documentation to include how to configure Jobs Service using the Operator.
@ricardozanini @kaldesai PTAL
=> [KOGITO-9940] Add documentation for Jobs Service support in the Operator

.github/workflows/pr-preview-publish.yml
Another quick one to fix this:
```
Run actions-cool/maintain-one-comment@v3
with:
token: ***
body: 🎊 PR Preview caf86c86[2](https://github.com/apache/incubator-kie-kogito-docs/actions/runs/8189571112/job/22394610894#step:4:2)ff0c5b020f2[4](https://github.com/apache/incubator-kie-kogito-docs/actions/runs/8189571112/job/22394610894#step:4:4)8d40d89[5](https://github.com/apache/incubator-kie-kogito-docs/actions/runs/8189571112/job/22394610894#step:4:5)d0d4a817b9d has been successfully built and deployed. See the documentation preview: https://sonataflow-docs-preview-pr-.surge.sh
body-include: 
emojis: heart
Now eventName: workflow_run. And input number is empty. This Action only support issue and pull_request related!
```
See https://github.com/apache/incubator-kie-kogito-docs/actions/runs/81 …
=> Add PR id to publish workflows

.github/workflows/pr-preview-publish.yml
Since we have a problem in the GitHub Actions ecosystem, we need a way to grab the PR ids. See more: https://github.com/orgs/community/discussions/25220
=> NO-ISSUE - Try to fix PR id not found in github event

.github/workflows/pr-preview-build.yml, .github/workflows/pr-preview-publish.yml
Yet another alternative to grab PR IDs from the `workflow_run` due to a GHA issue.
=> NO-ISSUE - Use yet another alternative to grab PR ID

serverlessworkflow/modules/ROOT/pages/cloud/operator/build-and-deploy-workflows.adoc
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them …
=> kie-kogito-docs-567: Add the MAVEN_ARGS_APPEND argument to the Building and Deploying Workflows with the Operator guide

serverlessworkflow/modules/ROOT/pages/cloud/operator/supporting-services.adoc
https://github.com/apache/incubator-kie-kogito-serverless-operator/pull/345
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific …
=> [KOGITO-9974] cluster-wide supporting services

serverlessworkflow/modules/ROOT/pages/cloud/index.adoc, serverlessworkflow/modules/ROOT/pages/cloud/operator/using-persistence.adoc
Adds documentation with examples on how to configure a `SonataFlow` CR with persistence using its own dedicated `persistence` field or leveraging on the `SonataFlowPlatform` CR persistence configuration.
@ricardozanini @wmedvede @caponetto PTAL.
=> [KOGITO-9982] Add persistence to SonataFlow CRD

serverlessworkflow/modules/ROOT/pages/core/timeouts-support.adoc
Closes/Fixes/Resolves #528 
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them from one …
=> kie-kogito-docs-528: Document timeout format limitation

.github/workflows/npm-publish-pages.yml, .github/workflows/sw-docs-pr.yml
Relates to #580 (I won't close it prior to this PR being merged since we will have a few tries until it works) 
In this PR, we try to use the default GHA to publish the website.
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, …
=> ISSUE-580: Use default GH Action to publish guides

serverlessworkflow/modules/ROOT/pages/core/understanding-jq-expressions.adoc
Fixes https://github.com/apache/incubator-kie-kogito-docs/issues/526
As per subject. Also adds function of type expression and more info on $SECRET data type.
=> [Fix #526] Document and give example of JSON in data

serverlessworkflow/modules/ROOT/pages/cloud/operator/build-and-deploy-workflows.adoc, serverlessworkflow/modules/ROOT/pages/cloud/operator/customize-podspec.adoc
Relates to https://github.com/apache/incubator-kie-kogito-serverless-operator/issues/319
Quick note about profiles and configuration.
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still …
=> Add a note about profiles and configuration properties

serverlessworkflow/modules/ROOT/nav.adoc, serverlessworkflow/modules/ROOT/pages/cloud/operator/configuring-knative-eventing-resources.adoc
doc for knative eventing in operator
=> doc for knative eventing in operator

serverlessworkflow/antora.yml, serverlessworkflow/modules/ROOT/nav.adoc, serverlessworkflow/modules/ROOT/pages/_common-content/getting-started-requirement-quarkus.adoc, serverlessworkflow/modules/ROOT/pages/_common-content/getting-started-requirement.adoc, serverlessworkflow/modules/ROOT/pages/getting-started/create-your-first-workflow-service-with-kn-cli-and-vscode.adoc, serverlessworkflow/modules/ROOT/pages/getting-started/learning-environment.adoc, serverlessworkflow/modules/ROOT/pages/getting-started/preparing-environment.adoc, serverlessworkflow/modules/ROOT/pages/getting-started/production-environment.adoc, serverlessworkflow/modules/ROOT/pages/index.adoc, serverlessworkflow/modules/ROOT/pages/use-cases/advanced-developer-use-cases/getting-started/build-workflow-image-with-quarkus-cli.adoc, serverlessworkflow/modules/ROOT/pages/use-cases/advanced-developer-use-cases/getting-started/create-your-first-workflow-service.adoc, serverlessworkflow/modules/ROOT/pages/use-cases/advanced-developer-use-cases/getting-started/working-with-serverless-workflow-quarkus-examples.adoc, serverlessworkflow/modules/ROOT/pages/use-cases/advanced-developer-use-cases/index.adoc, serverlessworkflow/modules/ROOT/pages/use-cases/advanced-developer-use-cases/persistence/integration-tests-with-postgresql.adoc, serverlessworkflow/modules/ROOT/pages/use-cases/advanced-developer-use-cases/persistence/persistence-with-postgresql.adoc, serverlessworkflow/modules/ROOT/pages/use-cases/advanced-developer-use-cases/testing/basic-integration-tests-with-restassured.adoc, serverlessworkflow/modules/ROOT/pages/use-cases/advanced-developer-use-cases/testing/mocking-openapi-services-with-wiremock.adoc
Resolves #574
Adds new chapters that should allow us to unify all environment configurations needed for users to work with our guides
=> kie-kogito-docs-574 - Add prepare environment guide for sonataflow 

serverlessworkflow/modules/ROOT/nav.adoc, serverlessworkflow/modules/ROOT/pages/core/custom-functions-support.adoc, serverlessworkflow/modules/ROOT/pages/use-cases/advanced-developer-use-cases/integrations/custom-functions-python.adoc
Fixes https://github.com/apache/incubator-kie-kogito-docs/issues/599
Add python documentation
=> [Fix #599] Add Python documentation

serverlessworkflow/antora.yml, serverlessworkflow/modules/ROOT/nav.adoc, serverlessworkflow/modules/ROOT/pages/getting-started/java-embedded-workflows.adoc, serverlessworkflow/modules/ROOT/pages/index.adoc
Documents java flow library
https://issues.redhat.com/browse/KOGITO-9454
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. …
=> [KOGITO-9454]  Documenting java flow library

serverlessworkflow/antora.yml, serverlessworkflow/modules/ROOT/nav.adoc, serverlessworkflow/modules/ROOT/pages/getting-started/create-your-first-workflow-service-with-kn-cli-and-vscode.adoc, serverlessworkflow/modules/ROOT/pages/getting-started/java-embedded-workflows.adoc, serverlessworkflow/modules/ROOT/pages/getting-started/learning-environment.adoc, serverlessworkflow/modules/ROOT/pages/integrations/core-concepts.adoc
Closes/Fixes/Resolves #601
Couple of fixes I collected.
=> [Fix #601] Fix SonataFlow docs issues found during SME reviews and consultations

serverlessworkflow/modules/ROOT/pages/getting-started/preparing-environment.adoc
- Removes `minikube config set cpus/memory` - this is already part of the `minikube start` command
- Splits setup to Minikube with Docker and Minikube with Podman - this would be easier for users to copy/paste the commands (the previous version needed to be modified)
=> NO-ISSUE: Improve Minikube setup

serverlessworkflow/modules/ROOT/pages/job-services/core-concepts.adoc
=> Issue-597 Holistic review of non-quarkus job service chapter

serverlessworkflow/modules/ROOT/pages/cloud/operator/build-and-deploy-workflows.adoc, serverlessworkflow/modules/ROOT/pages/data-index/data-index-core-concepts.adoc, serverlessworkflow/modules/ROOT/pages/data-index/data-index-service.adoc, serverlessworkflow/modules/ROOT/pages/eventing/event-correlation-with-workflows.adoc, serverlessworkflow/modules/ROOT/pages/testing-and-troubleshooting/quarkus-dev-ui-extension/quarkus-dev-ui-overview.adoc, serverlessworkflow/modules/ROOT/pages/testing-and-troubleshooting/quarkus-dev-ui-extension/quarkus-dev-ui-workflow-instances-page.adoc, serverlessworkflow/modules/ROOT/pages/use-cases/advanced-developer-use-cases/data-index/data-index-quarkus-extension.adoc, serverlessworkflow/modules/ROOT/pages/use-cases/advanced-developer-use-cases/deployments/common/_common_proc_deploy_kubectl_oc.adoc, serverlessworkflow/modules/ROOT/pages/use-cases/advanced-developer-use-cases/deployments/common/_proc_deploy_sw_quarkus_cli.adoc, serverlessworkflow/modules/ROOT/pages/use-cases/advanced-developer-use-cases/event-orchestration/consume-produce-events-with-knative-eventing.adoc, serverlessworkflow/modules/ROOT/pages/use-cases/advanced-developer-use-cases/integrations/custom-functions-knative.adoc, serverlessworkflow/modules/ROOT/pages/use-cases/advanced-developer-use-cases/integrations/expose-metrics-to-prometheus.adoc, serverlessworkflow/modules/ROOT/pages/use-cases/advanced-developer-use-cases/integrations/serverless-dashboard-with-runtime-data.adoc, serverlessworkflow/modules/ROOT/pages/use-cases/advanced-developer-use-cases/job-service/quarkus-extensions.adoc, serverlessworkflow/modules/ROOT/pages/use-cases/advanced-developer-use-cases/persistence/integration-tests-with-postgresql.adoc, serverlessworkflow/modules/ROOT/pages/use-cases/advanced-developer-use-cases/persistence/persistence-with-postgresql.adoc, serverlessworkflow/modules/ROOT/pages/use-cases/advanced-developer-use-cases/persistence/postgresql-flyway-migration.adoc, serverlessworkflow/modules/ROOT/pages/use-cases/advanced-developer-use-cases/service-discovery/kubernetes-service-discovery.adoc
Closes/Fixes/Resolves #598
**Description:**  Holistic review of non-quarkus data-index chapter.
Also fixed references to `kogito-addons` which have changed to `kie-addons`.
=> Issue-598 Holistic review of non-quarkus data index chapter

serverlessworkflow/modules/ROOT/pages/core/working-with-parallelism.adoc, serverlessworkflow/modules/ROOT/pages/use-cases/advanced-developer-use-cases/event-orchestration/newsletter-subscription-example.adoc, serverlessworkflow/modules/ROOT/pages/use-cases/advanced-developer-use-cases/getting-started/create-your-first-workflow-service.adoc, serverlessworkflow/modules/ROOT/pages/use-cases/advanced-developer-use-cases/service-orchestration/configuring-openapi-services-endpoints-with-quarkus.adoc
Closes/Fixes/Resolves #617 
**Description:** Replaces occurrences of specification version with `spec_version` attribute.
=> Issue-617 Replace specVersion with spec_version attribute

serverlessworkflow/antora.yml, serverlessworkflow/modules/ROOT/pages/core/custom-functions-support.adoc, serverlessworkflow/modules/ROOT/pages/getting-started/java-embedded-workflows.adoc
Fixes https://github.com/apache/incubator-kie-kogito-docs/issues/616
Add openapi, grpc, python and persistence examples to embedded executor guide
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring …
=> [Fix #616]  Adding dependency documentation to embedded

serverlessworkflow/modules/ROOT/nav.adoc, serverlessworkflow/modules/ROOT/pages/cloud/operator/add-custom-ca-to-a-workflow-pod.adoc
- **Fix memory unit from "mi:" to "Mi"**
- **Add a guide on how to add a CA to pod or serverless workflow**
Related-To: [FLPATH-1069](https://issues.redhat.com/browse/FLPATH-1069)
=> Add CA guide

serverlessworkflow/modules/ROOT/pages/cloud/operator/customize-podspec.adoc, serverlessworkflow/modules/ROOT/pages/cloud/operator/known-issues.adoc
Closes https://github.com/apache/incubator-kie-kogito-serverless-operator/issues/385
In this PR, we add a brief explanation about deploying workflows as Knative Services.
Depends on https://github.com/apache/incubator-kie-kogito-serverless-operator/pull/447
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move …
=> Add a note about Knative deployment model in the operator

serverlessworkflow/modules/ROOT/pages/use-cases/advanced-developer-use-cases/integrations/custom-functions-python.adoc
=> Fixing typo on Python guide

serverlessworkflow/antora.yml, serverlessworkflow/modules/ROOT/pages/getting-started/preparing-environment.adoc, serverlessworkflow/modules/ROOT/pages/job-services/core-concepts.adoc, serverlessworkflow/modules/ROOT/pages/use-cases/advanced-developer-use-cases/deployments/deploying-on-openshift.adoc
Closes #630 
<details>
<summary>
</summary> …
=> kie-kogito-docs-630: Jobs Service documentation still refers to mongodb, and infinispan

serverlessworkflow/antora.yml, serverlessworkflow/modules/ROOT/pages/security/orchestrating-third-party-services-with-oauth2.adoc, serverlessworkflow/modules/ROOT/pages/use-cases/advanced-developer-use-cases/deployments/common/_proc_deploy_sw_quarkus_cli.adoc, serverlessworkflow/modules/ROOT/pages/use-cases/advanced-developer-use-cases/event-orchestration/newsletter-subscription-example.adoc, serverlessworkflow/modules/ROOT/pages/use-cases/advanced-developer-use-cases/getting-started/build-workflow-image-with-quarkus-cli.adoc, serverlessworkflow/modules/ROOT/pages/use-cases/advanced-developer-use-cases/getting-started/working-with-serverless-workflow-quarkus-examples.adoc, serverlessworkflow/modules/ROOT/pages/use-cases/advanced-developer-use-cases/persistence/persistence-with-postgresql.adoc, serverlessworkflow/modules/ROOT/pages/use-cases/advanced-developer-use-cases/timeouts/timeout-showcase-example.adoc
Closes #593
In the security chapters the old name of the examples repository was used in the commands. This PR fixes also other use cases.
- Creates a new constant `kie_kogito_examples_repo_name` and replaces the occurrences in the docs. 
- Replaces kogito examples git url with `kogito_examples_url`
```yaml
kogito_examples_url: https://github.com/apache/incubator-kie-kogito-examples.git
kie_kogito_examples_repo_name: incubator-kie-kogito-examples
```
=> Replace kogito-examples with incubator-kie-kogito-examples

serverlessworkflow/modules/ROOT/pages/tooling/serverless-logic-web-tools/serverless-logic-web-tools-deploy-projects.adoc, serverlessworkflow/modules/ROOT/pages/tooling/serverless-logic-web-tools/serverless-logic-web-tools-github-integration.adoc, serverlessworkflow/modules/ROOT/pages/tooling/serverless-logic-web-tools/serverless-logic-web-tools-overview.adoc, serverlessworkflow/modules/ROOT/pages/tooling/serverless-logic-web-tools/serverless-logic-web-tools-redhat-application-services-integration.adoc, serverlessworkflow/modules/ROOT/pages/tooling/serverless-workflow-editor/swf-editor-chrome-extension.adoc, serverlessworkflow/modules/ROOT/pages/tooling/serverless-workflow-editor/swf-editor-overview.adoc, serverlessworkflow/modules/ROOT/pages/tooling/serverless-workflow-editor/swf-editor-vscode-extension.adoc
Closes/Fixes/Resolves #590
The pull request provides some fixes after holistic review of non-quarkus tooling guides for SonataFlow
=> Issue-590 Holistic review of non-quarkus tooling guides

serverlessworkflow/antora.yml, serverlessworkflow/modules/ROOT/pages/cloud/operator/configuring-knative-eventing-resources.adoc
Closes #627 
<details>
<summary>
</summary> …
=> kie-kogito-docs-672: Create a new SonataFlow guide for Knative Eventing Integration with Jobs Service and Data Index

serverlessworkflow/antora.yml, serverlessworkflow/modules/ROOT/pages/job-services/core-concepts.adoc, serverlessworkflow/modules/ROOT/pages/use-cases/advanced-developer-use-cases/timeouts/timeout-showcase-example.adoc
Closes #641 
<details>
<summary>
</summary> …
=>  kie-kogito-docs-641: Remove Job Service All in one image from documentation

serverlessworkflow/modules/ROOT/pages/core/understanding-jq-expressions.adoc
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them …
=> Fixing formatting issues

serverlessworkflow/modules/ROOT/pages/service-orchestration/orchestration-of-openapi-based-services.adoc
Closes/Fixes/Resolves #591 
**Holistic review of non-quarkus service orchestration chapter**
The PR introduce some readability improvements found during the chapter review.
I identified many issues that are out of the scope of this PR and are tracked here:
- https://github.com/apache/incubator-kie-kogito-docs/issues/657
- https://github.com/apache/incubator-kie-kogito-docs/issues/658
- https://github.com/apache/incubator-kie-kogito-docs/issues/659
=> Issue-591: Holistic review of non-quarkus service orchestration chapter

serverlessworkflow/antora.yml, serverlessworkflow/modules/ROOT/pages/getting-started/create-your-first-workflow-service-with-kn-cli-and-vscode.adoc
Closes/Fixes/Resolves #583
**Holistic review of non-quarkus getting-started chapter**
The PR updates some issues found during the chapter review.
There were identified the following issues that are out of the scope of this PR:
- https://github.com/apache/incubator-kie-kogito-docs/issues/649
- https://github.com/apache/incubator-kie-kogito-docs/issues/650
=> Issue-583: Holistic review of non-quarkus getting-started chapter

serverlessworkflow/modules/ROOT/pages/cloud/operator/supporting-services.adoc, serverlessworkflow/modules/ROOT/pages/data-index/data-index-service.adoc, serverlessworkflow/modules/ROOT/pages/job-services/core-concepts.adoc, serverlessworkflow/modules/ROOT/pages/persistence/core-concepts.adoc
Closes/Fixes/Resolves #595 
**Description:** Holistic review of non-quarkus persistence chapter. Some typos and broken links are being fixed.
<details>
<summary>
</summary> …
=> [Issue_595] Holistic review of non-quarkus persistence chapter

serverlessworkflow/modules/ROOT/pages/getting-started/preparing-environment.adoc, serverlessworkflow/modules/ROOT/pages/testing-and-troubleshooting/kn-plugin-workflow-overview.adoc
Closes/Fixes/Resolves #588 
**Holistic review of non-quarkus setup chapter**
The PR updates some issues found during the chapter review.
There was identified one issue that is **out of the scope** if this PR: https://github.com/apache/incubator-kie-kogito-docs/issues/647
=> Issue-588: Holistic review of non-quarkus setup chapter

serverlessworkflow/modules/ROOT/pages/cloud/operator/using-persistence.adoc
We are missing the `flow` attribute under `spec.properties`:
```shell
The SonataFlowPlatform "sonataflow-platform" is invalid: spec.properties: Invalid value: "array": spec.properties in body must be of type object: "array"
```
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch …
=> NO ISSUE - Fix a wrong attribute under platform spec.properties

serverlessworkflow/modules/ROOT/pages/testing-and-troubleshooting/kn-plugin-workflow-overview.adoc
Closes/Fixes/Resolves https://github.com/apache/incubator-kie-tools/issues/2486
Fixes to improve kn plugin workflow overview docs, found during https://github.com/apache/incubator-kie-tools/issues/2486
=> Fixes based on 10.0.x-kn-plugin-workflow review

serverlessworkflow/modules/ROOT/pages/cloud/operator/add-custom-ca-to-a-workflow-pod.adoc
Signed-off-by: Roy Golan <rgolan@redhat.com>
=> Add missing instruction on adding the CA configmap

serverlessworkflow/modules/ROOT/pages/core/understanding-jq-expressions.adoc
$ rather than . should be used for loop variable
Fix https://github.com/apache/incubator-kie-kogito-runtimes/issues/3694
To be merged with https://github.com/apache/incubator-kie-kogito-runtimes/pull/3696
=> [Fix #3694] Updating documentation

serverlessworkflow/modules/ROOT/pages/data-index/data-index-core-concepts.adoc
Resolves Issue #678 
`from` and `to` are not standalone operators.
They can only be used as part of the `between` operator.
<details>
<summary>
</summary> …
=> Issue-678 Improve `between` operator description

serverlessworkflow/modules/ROOT/pages/cloud/operator/supporting-services.adoc
Closes:  #664 
<details>
<summary>
</summary> …
=> kie-kogito-docs-664: Create a guide for the SonataFlow Operator driven Supporting Services Knative Eventing system configuration

antora-playbook.yml
As per current development practices, we should point to snapshot to not confuse users with deprecated references.
=> NO-ISSUE: Update antora-playbook.yml so the website points to main

serverlessworkflow/modules/ROOT/pages/use-cases/advanced-developer-use-cases/integrations/expose-metrics-to-prometheus.adoc
Fix https://github.com/apache/incubator-kie-kogito-docs/issues/687
=> [Fix #687] Updating metrics doc

serverlessworkflow/modules/ROOT/nav.adoc, serverlessworkflow/modules/ROOT/pages/cloud/operator/common/platform-scoped-eventing-system-configuration-example.adoc, serverlessworkflow/modules/ROOT/pages/cloud/operator/configuring-workflow-eventing-system.adoc, serverlessworkflow/modules/ROOT/pages/cloud/operator/supporting-services.adoc
Closes: #684 
<details>
<summary>
</summary> …
=> kie-kogito-docs-684: Create a guide for the SonataFlow Operator driven Worfklows Knative Eventing system configuration

serverlessworkflow/antora.yml, serverlessworkflow/modules/ROOT/pages/cloud/operator/build-and-deploy-workflows.adoc
Reverts apache/incubator-kie-kogito-docs#699
=> Revert "[10.0.x] NO_ISSUE: Update versions to 10.0.0"

serverlessworkflow/modules/ROOT/pages/cloud/operator/install-serverless-operator.adoc
I didnt realize there are appends, so I update the installation guide to just be more straightforward
```
kogito_operator_repository_rawcontent_url: https://raw.githubusercontent.com/apache/incubator-kie-tools/refs/heads/{operator_version}/packages/sonataflow-operator/
```
operator_version is main for main branch 10.0.0 for 10.0.x
=> NO_ISSUE: Improve manual operator installation

serverlessworkflow/antora.yml
Fixes operator rawcontent URL for the yml file used to manually install operator.
Only for `10.0.x` for next releases and on main I ll work on better solution
=> [10.0.x] NO_ISSUE: Fix URL to use tagged opeator.yml for 10.0.0

serverlessworkflow/modules/ROOT/pages/cloud/operator/referencing-resource-files.adoc
In this PR, we added a few notes about the operator ignoring `.specs.resources` in the gitops profile.
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping …
=> NO-ISSUE: Clarify that `.spec.resources`  is ignored in gitops

serverlessworkflow/modules/ROOT/pages/data-index/data-index-service.adoc
Refers to #738 
Changes example docker-compose data-index image from obsolete quay.io/kiegroup/... to {sonataflow_dataindex_postgresql_imagename}:{operator_version}
=> Issue-738 SonataFlow 'Data Index standalone service' doc quay.io image reference
