apache/incubator-kie-kogito-docs

- .github/workflows/sw-docs-pr.yml
Fixing GH action for PR antora build
> KOGITO-7273: Antora build fails on Pull Request GH action

- package.json
* adding npm scripts for Local dev
> KOGITO-7233: Configuring live-preview on netlify

- .github/workflows/sw-docs-pr.yml
[KOGITO-7233] - Updated build script
Signed-off-by: Achyut Madhusudan <amadhusu@redhat.com>
> [KOGITO-7233] - Updated build script

- package-lock.json
- We need to have `package-lock.json` file in root to ensure npm ci runs smoothly.
Refer: https://github.com/kiegroup/kogito-docs/pull/13
> KOGITO-7232: Push kogito-docs build to GH Pages

- antora-playbook-author.yml
- antora-playbook.yml
- serverlessworkflow/modules/ROOT/pages/cloud/build-workflow-image-with-quarkus-cli.adoc
- serverlessworkflow/modules/ROOT/pages/getting-started/create-your-first-workflow-service.adoc
Signed-off-by: spolti <fspolti@redhat.com>
> [KOGITO-7276] - fix small issues

- serverlessworkflow/modules/ROOT/nav.adoc
- serverlessworkflow/modules/ROOT/pages/service-orchestration/orchestration-of-grpc-services.adoc
> [KOGITO-7249] Guide for gRPC

- antora-playbook-author.yml
- antora-playbook.yml
- antora/supplemental-ui/css/navbar.css
- antora/supplemental-ui/css/tabs.css
- antora/supplemental-ui/js/tabsBehavior.js
- antora/supplemental-ui/partials/footer-scripts.hbs
- antora/supplemental-ui/partials/head-meta.hbs
- lib/tabs.js
* Added tabsets extension
* Changed navbar theme
How to create tabs in page:
```
[tabs]
====
Tab A::
+
[source,shell]
--
Contents of tab A.
--
Tab B::
+
[source,java]
--
Contents of tab B.
--
Tab C::
+
[source,c]
--
Contents of tab C.
--
====
```
**JIRA:**
> KOGITO-7417: Add switchable tabs in Antora

- .github/CODEOWNERS
Since Achyut is focusing on other tasks, we will remove him from this file to reduce the noise.
> Removing Achyut from CODEOWNERS

- antora-playbook.yml
**JIRA:**
https://issues.redhat.com/browse/KOGITO-7460
> Forcing antora to always fetch latest changes in git repository

- serverlessworkflow/antora.yml
> Update quarkus version

- .ci/jenkins/Jenkinsfile.post-release
- .ci/jenkins/dsl/jobs.groovy
- .ci/jenkins/dsl/test.sh
- .github/workflows/jenkins-tests-PR.yml
Depends on https://github.com/kiegroup/kogito-pipelines/pull/520
**JIRA:**
> Setup post release job

- serverlessworkflow/antora.yml
Related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/524
- https://github.com/kiegroup/drools/pull/4504
- https://github.com/kiegroup/kogito-runtimes/pull/2303
- https://github.com/kiegroup/kogito-examples/pull/1316
- https://github.com/kiegroup/kogito-docs/pull/44
> [main] Bump Quarkus version to 2.10.1.Final

- .ci/jenkins/dsl/jobs.groovy
Depends on https://github.com/kiegroup/kogito-pipelines/pull/525
**JIRA:**
> [KOGITO-7483] Setup quarkus update job

- antora/supplemental-ui/css/home.css
- antora/supplemental-ui/partials/head-meta.hbs
- serverlessworkflow/antora.yml
- serverlessworkflow/modules/ROOT/pages/index.adoc
* Added styling for creating cards/tiles on home page.
* to create a new card, follow this syntax
```
[.card-section]
== CATEGORY
[.card]
--
[.card-title]
xref:CATEGORY/PAGE_NAME.adoc[Card title]
[.card-description]
Card description
--
```
**JIRA:**
https://issues.redhat.com/browse/KOGITO-7464
> KOGITO-7464: Home Page for Serverless Workflow Guides

- serverlessworkflow/modules/ROOT/pages/getting-started/cncf-serverless-workflow-specification-support.adoc
Minor clarification of the level of compliance of our implementation with version 0.8  of the specification, regarding events
> Support event refinement

- serverlessworkflow/modules/ROOT/nav.adoc
- serverlessworkflow/modules/ROOT/pages/core/understanding-jq-expressions.adoc
**JIRA:https://issues.redhat.com/browse/KOGITO-7252**
**Description: Patch PR for KOGITO-7251**
https://github.com/kiegroup/kogito-docs/pull/30
> Patch PR for KOGITO-7251: Doc improvements for JQ expressions guide

- serverlessworkflow/modules/ROOT/pages/core/understanding-workflow-error-handling.adoc
> Fixing broken link in error handling guide

- serverlessworkflow/modules/ROOT/nav.adoc
- serverlessworkflow/modules/ROOT/pages/testing-and-troubleshooting/mocking-opnapi-services-with-wiremock.adoc
**JIRA:** https://issues.redhat.com/browse/KOGITO-7314
**Description:** Patch PR for KOGITO-7313 with doc improvements in "Mocking OpenAPI services using WireMock:
https://github.com/kiegroup/kogito-docs/pull/47
> KOGITO-7314: Patch PR for KOGITO-7313 with doc improvements

- serverlessworkflow/modules/ROOT/pages/getting-started/create-your-first-workflow-service.adoc
**JIRA:** https://issues.redhat.com/browse/KOGITO-7571
> KOGITO-7571 Updated getting started guide to not generate example code

- serverlessworkflow/modules/ROOT/nav.adoc
- serverlessworkflow/modules/ROOT/pages/index.adoc
- serverlessworkflow/modules/ROOT/pages/security/authention-support-for-openapi-services.adoc
- serverlessworkflow/modules/ROOT/pages/security/orchestrating-third-party-services-with-oauth2.adoc
- Adds the corresponding card to the index.adoc
**JIRA:**
> KOGITO-7263: [KSW-Guides] Orchestrating third party services with OAuth2 authentication

- serverlessworkflow/modules/ROOT/nav.adoc
- serverlessworkflow/modules/ROOT/pages/integrations/serverless-dashboard-with-runtime-data.adoc
**JIRA:**  https://issues.redhat.com/browse/KOGITO-7300
**Description:** Patch PR for KOGITO-7299 with doc improvements in dashboard doc
https://github.com/kiegroup/kogito-docs/pull/52
> KOGITO-7300: Patch PR for KOGITO-7299 with doc improvements in dashboard doc

- serverlessworkflow/modules/ROOT/nav.adoc
- serverlessworkflow/modules/ROOT/pages/security/authention-support-for-openapi-services.adoc
- serverlessworkflow/modules/ROOT/pages/security/orchestrating-third-party-services-with-oauth2.adoc
**JIRA:**https://issues.redhat.com/browse/KOGITO-7264
**Description:**Patch PR for KOGITO-7263 with doc improvements in OAuth2 authentication guide
https://github.com/kiegroup/kogito-docs/pull/29
> KOGITO-7264: Patch PR for KOGITO-7263 with doc improvements in OAuth2 authentication guide

- .github/pull_request_template.md
- CONTRIBUTING.md
- README.adoc
In this PR, we introduce the CONTRIBUTIONS doc.
**JIRA:** https://issues.redhat.com/browse/KOGITO-7324
> [KOGITO-7324] - Add the CONTRIBUTIONS.md

- serverlessworkflow/modules/ROOT/pages/_common-content/getting-started-requirement.adoc
- serverlessworkflow/modules/ROOT/pages/cloud/build-workflow-image-with-quarkus-cli.adoc
- serverlessworkflow/modules/ROOT/pages/cloud/deploying-on-minikube.adoc
- serverlessworkflow/modules/ROOT/pages/core/understanding-jq-expressions.adoc
- serverlessworkflow/modules/ROOT/pages/core/understanding-workflow-error-handling.adoc
- serverlessworkflow/modules/ROOT/pages/getting-started/cncf-serverless-workflow-specification-support.adoc
- serverlessworkflow/modules/ROOT/pages/security/orchestrating-third-party-services-with-oauth2.adoc
- serverlessworkflow/modules/ROOT/pages/service-orchestration/orchestration-of-grpc-services.adoc
- serverlessworkflow/modules/ROOT/pages/service-orchestration/orchestration-of-openapi-based-services.adoc
- serverlessworkflow/modules/ROOT/pages/testing-and-troubleshooting/basic-integration-tests-with-restassured.adoc
- serverlessworkflow/modules/ROOT/pages/testing-and-troubleshooting/mocking-openapi-services-with-wiremock.adoc
- serverlessworkflow/modules/ROOT/pages/tooling/kn-plugin-workflow-overview.adoc
- serverlessworkflow/modules/ROOT/pages/tooling/quarkus-dev-ui-extension/quarkus-dev-ui-workflow-instances-page.adoc
- serverlessworkflow/modules/ROOT/pages/tooling/serverless-workflow-editor/swf-editor-chrome-extension.adoc
- serverlessworkflow/modules/ROOT/pages/tooling/serverless-workflow-editor/swf-editor-vscode-extension.adoc
**JIRA:** https://issues.redhat.com/browse/KOGITO-7593
> KOGITO-7593 Referred getting started in prereqs and fixed typos

- .github/ISSUE_TEMPLATE/bug.md
- .github/ISSUE_TEMPLATE/enhancement.md
Follow up of [KOGITO-7324](https://issues.redhat.com/KOGITO-7324)
In this small PR, we are adding the issues templates for this repository.
> Add issues templates for enhancement and bugs

- CONTRIBUTING.md
Small patch to add the title conventions to the contribution doc.
> Add title conventions to CONTRIB

- .github/pull_request_template.md
- serverlessworkflow/modules/ROOT/pages/index.adoc
In this PR, I updated the home page with all the remaining cards for the PRs to be published. Also updated the PR template to remind the authors to update this file.
Must be merged after:
- #29 
- #45 
- #55 
- #54 
- #52 
- #47 
- #46 
- #37 
- #34 
- #32 
- #30 
- #29 
> Updating the home page with all cards about to be published

- serverlessworkflow/modules/ROOT/nav.adoc
- serverlessworkflow/modules/ROOT/pages/core/working-with-parallelism.adoc
- serverlessworkflow/modules/ROOT/pages/index.adoc
**JIRA:** https://issues.redhat.com/browse/KOGITO-6996
This PR depends on: https://github.com/kiegroup/kogito-examples/pull/1338
> KOGITO-6996 Added new guide: "Working with parallelism"

- serverlessworkflow/modules/ROOT/nav.adoc
- serverlessworkflow/modules/ROOT/pages/use-cases/orchestration-based-saga-pattern.adoc
**JIRA:** https://issues.redhat.com/browse/KOGITO-7244
**Description:** Patch PR for KOGITO-6806 with doc improvements in Saga example guide
https://github.com/kiegroup/kogito-docs/pull/37
> KOGITO-7244: Patch PR for KOGITO-6806 with doc improvements in Saga example guide

- serverlessworkflow/antora.yml
- serverlessworkflow/modules/ROOT/nav.adoc
- serverlessworkflow/modules/ROOT/pages/eventing/working-with-callbacks.adoc
**JIRA:** https://issues.redhat.com/browse/KOGITO-7256
**Description:** Patch PR for KOGITO-7255 with doc improvements in Callback guide
https://github.com/kiegroup/kogito-docs/pull/46
> KOGITO-7256: Patch PR for KOGITO-7255 with doc improvements in Callback guide

- serverlessworkflow/modules/ROOT/nav.adoc
- serverlessworkflow/modules/ROOT/pages/core/working-with-parallelism.adoc
- serverlessworkflow/modules/ROOT/pages/index.adoc
**JIRA:** https://issues.redhat.com/browse/KOGITO-7248
**Description:** Patch PR for KOGITO-6996 with doc improvements in parallelism guide
https://github.com/kiegroup/kogito-docs/pull/77
> KOGITO-7248: Patch PR for KOGITO-6996 with doc improvements in parallelism guide

- serverlessworkflow/modules/ROOT/pages/testing-and-troubleshooting/mocking-http-cloudevents-with-wiremock.adoc
**Description:** Small fix to add sintax highlight to a few code examples.
> Adding source highlighting to Mock CE guide

- serverlessworkflow/modules/ROOT/pages/service-orchestration/orchestration-of-grpc-services.adoc
JIRA: [KOGITO-7612](https://issues.redhat.com/browse/KOGITO-7612)
PR set:
* https://github.com/kiegroup/kogito-docs/pull/87
* https://github.com/kiegroup/kogito-examples/pull/1351
Extended the gRPC guide with streaming scenarios. I tried to kept it concise, not to repeat everything, just pinpoint differences to the simple gRPC scenario which was already described.
> KOGITO-7612 - [Kogito Guides] Implement gRPC streaming scenarios

- serverlessworkflow/antora.yml
- serverlessworkflow/modules/ROOT/nav.adoc
- serverlessworkflow/modules/ROOT/pages/eventing/consume-producing-events-with-kafka.adoc
- serverlessworkflow/modules/ROOT/pages/index.adoc
**JIRA:** https://issues.redhat.com/browse/KOGITO-7287
**Description:** Patch PR for KOGITO-7286 with doc improvements in Consuming and producing events with Kafka guide
https://github.com/kiegroup/kogito-docs/pull/54/
> KOGITO-7287: Patch PR for KOGITO-7286 with doc improvements in Consuming and producing events with Kafka guide

- serverlessworkflow/modules/ROOT/pages/tooling/kn-plugin-workflow-overview.adoc
Won't require `sudo` permissions since the user is copying the file to a local directory. Just giving execute permissions should do.
Also, MacOS might block users from running the application. I've added a small note to fix this problem and a link to the Apple Support page.
> Simplify the mac command line instructions

- serverlessworkflow/modules/ROOT/nav.adoc
- serverlessworkflow/modules/ROOT/pages/index.adoc
- serverlessworkflow/modules/ROOT/pages/testing-and-troubleshooting/integration-tests-with-postgresql.adoc
- serverlessworkflow/modules/ROOT/pages/testing-and-troubleshooting/mocking-http-cloudevents-with-wiremock.adoc
**JIRA:** https://issues.redhat.com/browse/KOGITO-7309
**Description:** Added Serverless Workflow integration test with postgreSQL
> KOGITO-7309 Integration tests with PostgreSQL

- serverlessworkflow/modules/ROOT/nav.adoc
- serverlessworkflow/modules/ROOT/pages/index.adoc
- serverlessworkflow/modules/ROOT/pages/testing-and-troubleshooting/integration-tests-with-postgresql.adoc
**JIRA:** https://issues.redhat.com/browse/KOGITO-7310
**Description:** Patch PR for KOGITO-7309 with doc improvements in Integration tests with PostgreSQL guide
https://github.com/kiegroup/kogito-docs/pull/34
> KOGITO-7310: Patch PR for KOGITO-7309 with doc improvements in Integration tests with PostgreSQL guide

- serverlessworkflow/modules/ROOT/nav.adoc
**Description:** Fixes a broken link
> Fixed broken link

- serverlessworkflow/modules/ROOT/pages/core/understanding-workflow-error-handling.adoc
**JIRA:** https://issues.redhat.com/browse/KOGITO-7453
**Related PR:** https://github.com/kiegroup/kogito-runtimes/pull/2315
> KOGITO-7453: Update workflow error handling guide to describe new ExceptionHandlerPolicy

- serverlessworkflow/modules/ROOT/nav.adoc
- serverlessworkflow/modules/ROOT/pages/index.adoc
- serverlessworkflow/modules/ROOT/pages/persistence/persistence-with-postgresql.adoc
**JIRA:** https://issues.redhat.com/browse/KOGITO-7302
**Description:** Patch PR for KOGITO-7301 with doc improvements in Persistence with PostgresSQL databases guide
https://github.com/kiegroup/kogito-docs/pull/75
> KOGITO-7302: Patch PR for KOGITO-7301 with doc improvements in Persistence with PostgresSQL databases guide

- serverlessworkflow/modules/ROOT/pages/index.adoc
- serverlessworkflow/modules/ROOT/pages/security/authention-support-for-openapi-services.adoc
- serverlessworkflow/modules/ROOT/pages/security/orchestrating-third-party-services-with-oauth2.adoc
**Description:** This PR fixes broken links
> Fixed broken links

- serverlessworkflow/modules/ROOT/nav.adoc
- serverlessworkflow/modules/ROOT/pages/core/configuration-properties.adoc
- serverlessworkflow/modules/ROOT/pages/index.adoc
The goal here is to simply describe the current configuration properties we have that are relevant to SW.
In case we want to rename, lets create JIRA to track it.
> KOGITO-7636 SW configuration properties guide

- serverlessworkflow/modules/ROOT/nav.adoc
- serverlessworkflow/modules/ROOT/pages/core/configuration-properties.adoc
- serverlessworkflow/modules/ROOT/pages/index.adoc
**JIRA:** https://issues.redhat.com/browse/KOGITO-7637
**Description:** Patch PR for KOGITO-7636 with doc improvements in configuration properties
https://github.com/kiegroup/kogito-docs/pull/84
> KOGITO-7637: Patch PR for KOGITO-7636 with doc improvements in configuration properties

- serverlessworkflow/antora.yml
Reverts kiegroup/kogito-docs#98
> Revert "[main] Bump Quarkus version to 2.11.1.Final"

- .github/CODEOWNERS
- package-lock.json
- serverlessworkflow/antora.yml
- serverlessworkflow/modules/ROOT/pages/_common-content/productized-instructions.adoc
- serverlessworkflow/modules/ROOT/pages/getting-started/create-your-first-workflow-service.adoc
**JIRA:** https://issues.redhat.com/browse/KOGITO-7610
**Description:** In this JIRA we are adding the option to include content exclusive to downstream.
> [KOGITO-7610] - Adding downstream content to upstream 

- serverlessworkflow/modules/ROOT/nav.adoc
- serverlessworkflow/modules/ROOT/pages/index.adoc
- serverlessworkflow/modules/ROOT/pages/security/authention-support-for-openapi-services.adoc
- serverlessworkflow/modules/ROOT/pages/security/orchestrating-third-party-services-with-oauth2.adoc
- serverlessworkflow/modules/ROOT/pages/service-orchestration/configuring-openapi-services-endpoints.adoc
- serverlessworkflow/modules/ROOT/pages/service-orchestration/orchestration-of-openapi-based-services.adoc
**JIRA:** https://issues.redhat.com/browse/KOGITO-6998
This PR depends on: https://github.com/kiegroup/kogito-examples/pull/1354
> KOGITO-6998 Added configuring-openapi-services-endpoints guide

- serverlessworkflow/modules/ROOT/nav.adoc
- serverlessworkflow/modules/ROOT/pages/index.adoc
- serverlessworkflow/modules/ROOT/pages/security/authention-support-for-openapi-services.adoc
- serverlessworkflow/modules/ROOT/pages/security/orchestrating-third-party-services-with-oauth2.adoc
- serverlessworkflow/modules/ROOT/pages/service-orchestration/configuring-openapi-services-endpoints.adoc
**JIRA:** https://issues.redhat.com/browse/KOGITO-7245
**Description:** Patch PR for KOGITO-6998 with doc improvements in Configuring OpenAPI services endpoints guide
https://github.com/kiegroup/kogito-docs/pull/92
> KOGITO-7245: Patch PR for KOGITO-6998 with doc improvements in Configuring OpenAPI services endpoints guide

- serverlessworkflow/modules/ROOT/nav.adoc
- serverlessworkflow/modules/ROOT/pages/eventing/consume-produce-events-with-knative-eventing.adoc
- serverlessworkflow/modules/ROOT/pages/eventing/consume-producing-events-with-kafka.adoc
**JIRA:** https://issues.redhat.com/browse/KOGITO-7267
**Description:** In this PR, we introduce the new guide explaining the integration with Knative Eventing.
> [KOGITO-7267] - Consuming and producing events on Knative Eventing

- serverlessworkflow/antora.yml
- serverlessworkflow/modules/ROOT/pages/getting-started/create-your-first-workflow-service.adoc
**JIRA:** https://issues.redhat.com/browse/KOGITO-7691
> KOGITO-7691 Fixed unresolved variables in getting started guide

- serverlessworkflow/antora.yml
- serverlessworkflow/modules/ROOT/pages/core/configuration-properties.adoc
- serverlessworkflow/modules/ROOT/pages/eventing/working-with-callbacks.adoc
- serverlessworkflow/modules/ROOT/pages/index.adoc
- serverlessworkflow/modules/ROOT/pages/persistence/persistence-with-postgresql.adoc
- serverlessworkflow/modules/ROOT/pages/testing-and-troubleshooting/basic-integration-tests-with-restassured.adoc
**JIRA:** https://issues.redhat.com/browse/KOGITO-7708
**Description:** getting rid of the annoying warns, fixing references and attributes.
> [KOGITO-7708] Fix references and missing attributes

- serverlessworkflow/modules/ROOT/pages/core/working-with-parallelism.adoc
- serverlessworkflow/modules/ROOT/pages/security/authention-support-for-openapi-services.adoc
- serverlessworkflow/modules/ROOT/pages/security/orchestrating-third-party-services-with-oauth2.adoc
- serverlessworkflow/modules/ROOT/pages/service-orchestration/configuring-openapi-services-endpoints.adoc
- serverlessworkflow/modules/ROOT/pages/service-orchestration/orchestration-of-openapi-based-services.adoc
> Small fixes after guides review

- serverlessworkflow/modules/ROOT/nav.adoc
- serverlessworkflow/modules/ROOT/pages/getting-started/getting-familiar-with-our-tooling.adoc
- serverlessworkflow/modules/ROOT/pages/index.adoc
- serverlessworkflow/modules/ROOT/pages/tooling/serverless-workflow-editor/swf-editor-overview.adoc
**JIRA:** https://issues.redhat.com/browse/KOGITO-7269
> [KOGITO-7269] [KSW-Guides] Getting familiar with our tooling

- serverlessworkflow/modules/ROOT/pages/core/configuration-properties.adoc
**JIRA:**
https://issues.redhat.com/browse/KOGITO-7698
> [KOGITO-7698] Adding incoming and outgoing addon properties

- serverlessworkflow/modules/ROOT/nav.adoc
- serverlessworkflow/modules/ROOT/pages/getting-started/getting-familiar-with-our-tooling.adoc
- serverlessworkflow/modules/ROOT/pages/index.adoc
**JIRA:** https://issues.redhat.com/browse/KOGITO-7270
**Description:** Patch PR for KOGITO-7269 with doc improvements in tooling guide
https://github.com/kiegroup/kogito-docs/pull/113
> KOGITO-7270: Patch PR for KOGITO-7269 with doc improvements in tooling guide

- serverlessworkflow/modules/ROOT/nav.adoc
- serverlessworkflow/modules/ROOT/pages/eventing/handling-events-on-workflows.adoc
- serverlessworkflow/modules/ROOT/pages/index.adoc
**JIRA:** https://issues.redhat.com/browse/KOGITO-7292
**Description:** Patch PR for KOGITO-7290 with doc improvements in Handling events on workflows guide
https://github.com/kiegroup/kogito-docs/pull/100
> KOGITO-7292: Patch PR for KOGITO-7290 with doc improvements in Handling events on workflows guide

- serverlessworkflow/modules/ROOT/pages/security/orchestrating-third-party-services-with-oauth2.adoc
> Small fix in orchestrating-third-party-services-with-oauth2.adoc

- serverlessworkflow/antora.yml
See https://github.com/quarkusio/quarkus/blob/2.10/core/deployment/src/main/java/io/quarkus/deployment/pkg/steps/GraalVM.java#L32
**JIRA:**
> Update GraalVM version

- serverlessworkflow/antora.yml
> [1.24.x] Update project version

- serverlessworkflow/antora.yml
> [1.25.x] Update project version

- antora-playbook-author.yml
- antora-playbook.yml
- antora/supplemental-ui/css/custom.css
> Added antora lunr cofiguration to index search in only latest

- serverlessworkflow/antora.yml
> Update Quarkus and Maven versions

- serverlessworkflow/modules/ROOT/pages/security/orchestrating-third-party-services-with-oauth2.adoc
* Small fix in orchestrating-third-party-services-with-oauth2.adoc
* Small fix in orchestrating-third-party-services-with-oauth2.adoc
- review suggestions 1
* Small fix in orchestrating-third-party-services-with-oauth2.adoc
- review suggestions 2
(cherry picked from commit 604dbc2f8596fc8d6ee86ee227e366f01c525c6f)
**JIRA:**
> [1.24.x] Small fix in orchestrating-third-party-services-with-oauth2.adoc

- serverlessworkflow/modules/ROOT/pages/security/orchestrating-third-party-services-with-oauth2.adoc
* Small fix in orchestrating-third-party-services-with-oauth2.adoc
* Small fix in orchestrating-third-party-services-with-oauth2.adoc
- review suggestions 1
* Small fix in orchestrating-third-party-services-with-oauth2.adoc
- review suggestions 2
(cherry picked from commit 604dbc2f8596fc8d6ee86ee227e366f01c525c6f)
**JIRA:**
> [1.25.x] Small fix in orchestrating-third-party-services-with-oauth2.adoc

- serverlessworkflow/modules/ROOT/pages/_common-content/productized-instructions.adoc
**Description:** Small patch to update the RHBQ instructions.
> Updating RHBQ procedure

- serverlessworkflow/modules/ROOT/pages/cloud/build-workflow-image-with-quarkus-cli.adoc
- serverlessworkflow/modules/ROOT/pages/cloud/deploying-on-minikube.adoc
> Fixes after Cloud guides review

- serverlessworkflow/modules/ROOT/pages/_common-content/productized-instructions.adoc
- serverlessworkflow/modules/ROOT/pages/cloud/build-workflow-image-with-quarkus-cli.adoc
- serverlessworkflow/modules/ROOT/pages/cloud/deploying-on-minikube.adoc
Cherry-pick for #128 and #120.
> [1.24.x] RHBQ Procedure / Fix after Cloud guides review

- serverlessworkflow/modules/ROOT/pages/_common-content/productized-instructions.adoc
- serverlessworkflow/modules/ROOT/pages/cloud/build-workflow-image-with-quarkus-cli.adoc
- serverlessworkflow/modules/ROOT/pages/cloud/deploying-on-minikube.adoc
Cherry-pick for https://github.com/kiegroup/kogito-docs/pull/128 and https://github.com/kiegroup/kogito-docs/pull/120.
> [1.25.x] RHBQ Procedure / Fix after Cloud guides review

- serverlessworkflow/modules/ROOT/pages/_common-content/productized-instructions.adoc
- serverlessworkflow/modules/ROOT/pages/cloud/build-workflow-image-with-quarkus-cli.adoc
- serverlessworkflow/modules/ROOT/pages/cloud/deploying-on-minikube.adoc
Cherry-pick for https://github.com/kiegroup/kogito-docs/pull/128 and https://github.com/kiegroup/kogito-docs/pull/120.
> [1.26.x] RHBQ Procedure / Fix after Cloud guides review

- serverlessworkflow/antora.yml
- serverlessworkflow/modules/ROOT/pages/_common-content/downstream-post-create-project.adoc
- serverlessworkflow/modules/ROOT/pages/_common-content/downstream-project-setup-instructions.adoc
- serverlessworkflow/modules/ROOT/pages/cloud/build-workflow-image-with-quarkus-cli.adoc
- serverlessworkflow/modules/ROOT/pages/getting-started/create-your-first-workflow-service.adoc
- serverlessworkflow/modules/ROOT/pages/tooling/kn-plugin-workflow-overview.adoc
> [1.25.x] - Fix RHBQ procedure, add image procedure

- serverlessworkflow/antora.yml
- serverlessworkflow/modules/ROOT/pages/_common-content/downstream-post-create-project.adoc
- serverlessworkflow/modules/ROOT/pages/_common-content/downstream-project-setup-instructions.adoc
- serverlessworkflow/modules/ROOT/pages/cloud/build-workflow-image-with-quarkus-cli.adoc
- serverlessworkflow/modules/ROOT/pages/getting-started/create-your-first-workflow-service.adoc
- serverlessworkflow/modules/ROOT/pages/tooling/kn-plugin-workflow-overview.adoc
> [1.26.x] - Fix RHBQ procedure, add image procedure

- serverlessworkflow/antora.yml
- serverlessworkflow/modules/ROOT/pages/cloud/deploying-on-minikube.adoc
- serverlessworkflow/modules/ROOT/pages/getting-started/create-your-first-workflow-service.adoc
- serverlessworkflow/modules/ROOT/pages/tooling/kn-plugin-workflow-overview.adoc
**JIRA:** https://issues.redhat.com/browse/KOGITO-7694
This PR is a cherry-pick from https://github.com/kiegroup/kogito-docs/pull/135
> [1.24.x] KOGITO-7694 Fixed kn commands in create-your-first-workflow-service.adoc 

- antora-playbook-author.yml
- antora-playbook.yml
- serverlessworkflow/antora.yml
- serverlessworkflow/modules/ROOT/pages/cloud/build-workflow-image-with-quarkus-cli.adoc
- serverlessworkflow/modules/ROOT/pages/getting-started/create-your-first-workflow-service.adoc
- serverlessworkflow/modules/ROOT/pages/testing-and-troubleshooting/basic-integration-tests-with-restassured.adoc
**JIRA:** https://issues.redhat.com/browse/KOGITO-7761
**Description:** Cherry pick for KOGITO-7761
> [1.24.x][KOGITO-7761] Fix snapshot, latest versions and ref URLs

- antora-playbook-author.yml
- antora-playbook.yml
- serverlessworkflow/antora.yml
- serverlessworkflow/modules/ROOT/pages/cloud/build-workflow-image-with-quarkus-cli.adoc
- serverlessworkflow/modules/ROOT/pages/getting-started/create-your-first-workflow-service.adoc
- serverlessworkflow/modules/ROOT/pages/testing-and-troubleshooting/basic-integration-tests-with-restassured.adoc
**JIRA:** https://issues.redhat.com/browse/KOGITO-7761
**Description:** Cherry Pick for KOGITO-7761
> [1.25.x][KOGITO-7761] Fix snapshot, latest versions and ref URLs

- antora-playbook-author.yml
- antora-playbook.yml
- serverlessworkflow/antora.yml
- serverlessworkflow/modules/ROOT/pages/cloud/build-workflow-image-with-quarkus-cli.adoc
- serverlessworkflow/modules/ROOT/pages/getting-started/create-your-first-workflow-service.adoc
- serverlessworkflow/modules/ROOT/pages/testing-and-troubleshooting/basic-integration-tests-with-restassured.adoc
**JIRA:** https://issues.redhat.com/browse/KOGITO-7761
**Description:** Fix the display and component version, also cherry-pick KOGITO-7761
> [1.26.x][KOGITO-7761] Fix snapshot, latest versions and ref URLs

- antora-playbook-author.yml
- antora-playbook.yml
- serverlessworkflow/antora.yml
- serverlessworkflow/modules/ROOT/pages/cloud/build-workflow-image-with-quarkus-cli.adoc
- serverlessworkflow/modules/ROOT/pages/getting-started/create-your-first-workflow-service.adoc
- serverlessworkflow/modules/ROOT/pages/testing-and-troubleshooting/basic-integration-tests-with-restassured.adoc
**JIRA:** https://issues.redhat.com/browse/KOGITO-7761
**Description:** Fix latest and snapshot URLs versions
Blocked by:
- https://github.com/kiegroup/kogito-docs/pull/152
> [KOGITO-7761] Fix snapshot, latest versions and ref URLs

- serverlessworkflow/antora.yml
> [1.26.x] Setup rc prerelease

- .ci/jenkins/Jenkinsfile.init
- .ci/jenkins/dsl/jobs.groovy
Depends on https://github.com/kiegroup/kogito-pipelines/pull/579
Init example updates:
- 1.26.x branch: https://github.com/radtriste/kogito-docs/commit/09e9ceb024be2e134b09847b46a0513416abff4a
- main branch: https://github.com/radtriste/kogito-docs/commit/e391432980b8c352621eeb8f55912b5e7e2c071d
Post release updates:
- 1.26.x branch: https://github.com/radtriste/kogito-docs/commit/0fb30dd90a827b73be5ec0910492d781c0fedbe3
- https://github.com/radtriste/kogito-docs/releases/tag/1.26.0.Final
> KOGITO-7715 Pipelines: setup init job

- antora-playbook.yml
Depends on https://github.com/kiegroup/kogito-docs/pull/158
**JIRA:**
> Add branch 1.26.x

- serverlessworkflow/modules/ROOT/pages/cloud/deploying-on-minikube.adoc
- serverlessworkflow/modules/ROOT/pages/getting-started/create-your-first-workflow-service.adoc
- serverlessworkflow/modules/ROOT/pages/tooling/kn-plugin-workflow-overview.adoc
**JIRA:** https://issues.redhat.com/browse/KOGITO-7694
This PR is a cherry-pick from https://github.com/kiegroup/kogito-docs/pull/135
> [1.25.x] KOGITO-7694 Fixed kn commands in create-your-first-workflow-service.adoc

- serverlessworkflow/modules/ROOT/pages/cloud/deploying-on-minikube.adoc
- serverlessworkflow/modules/ROOT/pages/getting-started/create-your-first-workflow-service.adoc
- serverlessworkflow/modules/ROOT/pages/tooling/kn-plugin-workflow-overview.adoc
JIRA: https://issues.redhat.com/browse/KOGITO-7694
This PR is a cherry-pick from https://github.com/kiegroup/kogito-docs/pull/135
> [1.26.x] KOGITO-7694 Fixed kn commands in create-your-first-workflow-service.adoc

- serverlessworkflow/modules/ROOT/pages/service-orchestration/configuring-openapi-services-endpoints.adoc
> [KOGITO-6998] Adding alias configuration option

- serverlessworkflow/modules/ROOT/pages/core/configuration-properties.adoc
- serverlessworkflow/modules/ROOT/pages/service-orchestration/orchestration-of-grpc-services.adoc
Including properties and describing enum default behaviour
**JIRA:**
https://issues.redhat.com/browse/KOGITO-7705
> [KOGITO-7705 Updating grpc documentation

- serverlessworkflow/antora.yml
- serverlessworkflow/modules/ROOT/pages/_common-content/downstream-project-setup-instructions.adoc
- serverlessworkflow/modules/ROOT/pages/getting-started/create-your-first-workflow-service.adoc
- serverlessworkflow/modules/ROOT/pages/tooling/kn-plugin-workflow-overview.adoc
> [1.26.x][KOGITO-7767] - Fix Maven instructions to add earlyaccess config

- serverlessworkflow/antora.yml
- serverlessworkflow/modules/ROOT/pages/_common-content/downstream-project-setup-instructions.adoc
- serverlessworkflow/modules/ROOT/pages/getting-started/create-your-first-workflow-service.adoc
- serverlessworkflow/modules/ROOT/pages/tooling/kn-plugin-workflow-overview.adoc
> [1.25.x][KOGITO-7767] - Fix Maven instructions to add earlyaccess config

- serverlessworkflow/antora.yml
- serverlessworkflow/modules/ROOT/pages/_common-content/downstream-project-setup-instructions.adoc
- serverlessworkflow/modules/ROOT/pages/getting-started/create-your-first-workflow-service.adoc
- serverlessworkflow/modules/ROOT/pages/tooling/kn-plugin-workflow-overview.adoc
> [1.24.x][KOGITO-7767] - Fix Maven instructions to add earlyaccess config

- serverlessworkflow/modules/ROOT/pages/cloud/deploying-on-minikube.adoc
- serverlessworkflow/modules/ROOT/pages/getting-started/create-your-first-workflow-service.adoc
- serverlessworkflow/modules/ROOT/pages/tooling/kn-plugin-workflow-overview.adoc
**JIRA:**
- [NA] The nav.adoc file has a link to this guide in the proper category
- [ NA] The index.adoc file has a card to this guide in the proper category, with a meaningful description
> KOGITO-7783 - Update docs to better describe Knative workflow CLI deliverable

- serverlessworkflow/modules/ROOT/nav.adoc
- serverlessworkflow/modules/ROOT/pages/core/defining-an-input-schema-for-workflows.adoc
- serverlessworkflow/modules/ROOT/pages/index.adoc
Jira- https://issues.redhat.com/browse/KOGITO-7259
Created a guide to define a datainputschema in a workflow definition.
> KOGITO-7259- [KSW-Guides] Defining an input schema for Workflows

- README.adoc
Signed-off-by: spolti <fspolti@redhat.com>
**JIRA:**
<details>
<summary>
</summary>
</details>
> add published docs link on the readme

- serverlessworkflow/antora.yml
- serverlessworkflow/modules/ROOT/pages/core/defining-an-input-schema-for-workflows.adoc
- serverlessworkflow/modules/ROOT/pages/service-orchestration/orchestration-of-openapi-based-services.adoc
**JIRA:** https://issues.redhat.com/browse/KOGITO-7794
**Description:** Correct links/texts
Related PRs:
- https://github.com/kiegroup/kogito-docs/pull/151
<details>
<summary>
</summary> …
> KOGITO-7794 Correct input schema guide

- .github/CODEOWNERS
> Adding QE to code owners

- .github/workflows/cherry-pick.yml
Small fix in the GHA to add the correct number with the 🍒
> Fix cherry-pick label in GHA

- serverlessworkflow/modules/ROOT/pages/service-orchestration/configuring-openapi-services-endpoints.adoc
**JIRA:** https://issues.redhat.com/browse/KOGITO-7860
<details>
<summary>
</summary>
</details>
> KOGITO-7860 Fix the `stock-portfolio-service` name

- serverlessworkflow/antora.yml
**JIRA:**
<details>
<summary>
</summary>
</details>
> [1.26.x] Correct display version

- serverlessworkflow/modules/ROOT/pages/release_notes.adoc
**JIRA:**
Update the Release Notes page for 1.27.0.Final.
<details>
<summary>
</summary>
</details>
> [1.27.x] Release Notes for 1.27.0.Final

- serverlessworkflow/modules/ROOT/pages/core/custom-functions-support.adoc
**JIRA:**
This guide was outdated. Parameter signature does not need to a json node. Also KogitoProcessContext functionality needs to be documented
<details>
<summary>
</summary>
*NOTE: You can still add label after the merge and it should still be …
> Updating CNCF Custom Functions Guide

- serverlessworkflow/modules/ROOT/nav.adoc
- serverlessworkflow/modules/ROOT/pages/index.adoc
- serverlessworkflow/modules/ROOT/pages/integrations/expose-metrics-to-prometheus.adoc
**JIRA:** https://issues.redhat.com/browse/KOGITO-7298
**Description:** Patch PR for KOGITO-7297 with doc improvement to exposing workflow metrics guide
https://github.com/kiegroup/kogito-docs/pull/57
<details>
<summary>
</summary>
*NOTE: You can still add label after the merge …
> KOGITO-7298: Patch PR for KOGITO-7297 with doc improvement to exposing workflow metrics guide

- serverlessworkflow/modules/ROOT/pages/release_notes.adoc
Small patch to add release notes for 1.28.0.Final version
> [1.28.x] - Release Notes for 1.28.x

- .ci/jenkins/Jenkinsfile.init-branch
- .ci/jenkins/Jenkinsfile.post-release
https://issues.redhat.com/browse/KOGITO-8043
Related:
- https://github.com/kiegroup/kogito-pipelines/pull/632
- https://github.com/kiegroup/kogito-pipelines/pull/633
- https://github.com/kiegroup/drools/pull/4724
- https://github.com/kiegroup/kogito-runtimes/pull/2526
- https://github.com/kiegroup/kogito-apps/pull/1484
- https://github.com/kiegroup/kogito-examples/pull/1424
- https://github.com/kiegroup/kogito-images/pull/1343
- https://github.com/kiegroup/kogito-operator/pull/1294
- https://github.com/kiegroup/kogito-docs/pull/219
> [1.27.x] KOGITO-8043 Jenkins node master -> built-in

- .ci/jenkins/Jenkinsfile.setup-branch
- .ci/jenkins/dsl/jobs.groovy
https://issues.redhat.com/browse/KOGITO-7798
Related PRs:
- https://github.com/kiegroup/kogito-pipelines/pull/602
- https://github.com/kiegroup/drools/pull/4713
- https://github.com/kiegroup/kogito-runtimes/pull/2502/files
- https://github.com/kiegroup/kogito-apps/pull/1471/files
- https://github.com/kiegroup/kogito-examples/pull/1414
- https://github.com/kiegroup/kogito-images/pull/1340
- https://github.com/kiegroup/kogito-operator/pull/1288
- https://github.com/kiegroup/kogito-docs/pull/214
> KOGITO-7798 Refactor setup branch job

- serverlessworkflow/modules/ROOT/pages/service-orchestration/orchestration-of-grpc-services.adoc
**JIRA:** https://issues.redhat.com/browse/KOGITO-7967
<details>
<summary>
</summary>
</details>
> KOGITO-7967 Improve clarity of procedure to start gRPC application in the guide

- .ci/jenkins/dsl/test.sh
- .github/workflows/cherry-pick.yml
- .github/workflows/jenkins-tests-PR.yml
- .github/workflows/sw-docs-pr.yml
https://issues.redhat.com/browse/KOGITO-8110
- https://github.com/kiegroup/kogito-pipelines/pull/646
- https://github.com/kiegroup/drools/pull/4738
- https://github.com/kiegroup/kogito-runtimes/pull/2547
- https://github.com/kiegroup/kogito-apps/pull/1489
- https://github.com/kiegroup/kogito-examples/pull/1440
- https://github.com/kiegroup/kogito-images/pull/1348
- https://github.com/kiegroup/kogito-operator/pull/1305
- https://github.com/kiegroup/kogito-docs/pull/228
- https://github.com/kiegroup/optaplanner/pull/2242
- https://github.com/kiegroup/optaweb-vehicle-routing/pull/770
- https://github.com/kiegroup/optaplanner-quickstarts/pull/428
- https://github.com/kiegroup/kie-tools/pull/1271
> KOGITO-8110 Correct GHA DSL checks

- serverlessworkflow/antora.yml
- serverlessworkflow/modules/ROOT/pages/security/orchestrating-third-party-services-with-oauth2.adoc
- Updates the Prerequisites for the guide
**JIRA:**
<details>
<summary>
</summary>
</details>
> Orchestrating third party services with oauth2 updates

- serverlessworkflow/modules/ROOT/pages/security/authention-support-for-openapi-services.adoc
**JIRA:** https://issues.redhat.com/browse/KOGITO-8145
<details>
<summary>
</summary>
</details>
> KOGITO-8145 Fix broken links in SWF Guide - section Security

- serverlessworkflow/modules/ROOT/pages/release_notes.adoc
Release Notes for 1.29.0.Final.
> [1.29.x] Release notes for 1.29.0.Final

- serverlessworkflow/modules/ROOT/pages/_common-content/downstream-post-create-project.adoc
Cherry pick from https://github.com/openshift-knative/docs/pull/80
> Remove Data Index image property definition for downstream doc

- serverlessworkflow/modules/ROOT/pages/getting-started/cncf-serverless-workflow-specification-support.adoc
**JIRA:**
<details>
<summary>
</summary>
</details>
> [KOGITO-8159] Event state not starting state if exclusive=false

- serverlessworkflow/modules/ROOT/pages/release_notes.adoc
**JIRA:**
<details>
<summary>
</summary>
</details>
> [1.30.x] Release notes for 1.30.0

- .ci/jenkins/Jenkinsfile.post-release
- .ci/jenkins/Jenkinsfile.setup-branch
Backport https://github.com/kiegroup/kogito-docs/pull/251
> Update version jenkinsfiles

- serverlessworkflow/modules/ROOT/pages/release_notes.adoc
On hold until we wrap up the release of the new version.
> [1.31.x] Release notes for 1.31.0

- serverlessworkflow/modules/ROOT/pages/core/timeouts-support.adoc
Signed-off-by: spolti <fspolti@redhat.com>
**JIRA:**
<details>
<summary>
</summary>
</details>
> [KOGITO-8304] - Document the usage of all-in-one jobs-service image

- serverlessworkflow/modules/ROOT/pages/release_notes.adoc
**JIRA:**
<details>
<summary>
</summary>
</details>
> [1.31.x] Update release notes for 1.31.1.Final

- .ci/jenkins/dsl/jobs.groovy
**JIRA:**
<details>
<summary>
</summary>
</details>
> KOGITO-8062 DSL: Refactor environments and export to config

- serverlessworkflow/modules/ROOT/pages/release_notes.adoc
Quick update to make Release Notes available for 1.32.0.Final version.
> [1.32.x] - Release Notes for 1.32.0.Final version

- .github/workflows/npm-publish-pages.yml
- scripts/copy-latest.py
**JIRA:** https://issues.redhat.com/browse/KOGITO-8408
**Description:** In this JIRA we add a workaround to the Antora navigation process since we don't have redirects in GH Pages. It's a Python script in the publish action to make a copy of the current latest to a numbered version. It worked on my machine. 🤭
<details>
<summary>
</summary>
In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-7.67.x` to backport the …
> [KOGITO-8408] Copying latest to numbered version

- antora/supplemental-ui/css/home.css
- serverlessworkflow/modules/ROOT/nav.adoc
- serverlessworkflow/modules/ROOT/pages/index.adoc
- serverlessworkflow/modules/ROOT/pages/persistence/postgresql-flyway-migration.adoc
**JIRA:**
[KOGITO-7503](https://issues.redhat.com/browse/KOGITO-7503)
<details>
<summary>
</summary>
</details>
> Adding Postgres DB migration guide

- serverlessworkflow/modules/ROOT/pages/release_notes.adoc
If you have a noteworthy JIRA and it's not on the list, make sure that it's in the right `component` AND `fixedVersion`.
> [1.33.x] Release Notes for 1.33.0

- serverlessworkflow/modules/ROOT/pages/core/timeouts-support.adoc
- serverlessworkflow/modules/ROOT/pages/getting-started/cncf-serverless-workflow-specification-support.adoc
**JIRA:**
https://issues.redhat.com/browse/KOGITO-8249
> [KOGITO-8249] Updating timeouts guide

- serverlessworkflow/modules/ROOT/nav.adoc
- serverlessworkflow/modules/ROOT/pages/index.adoc
- serverlessworkflow/modules/ROOT/pages/service-orchestration/orchestration-of-asyncapi-based-services.adoc
**JIRA:**
https://issues.redhat.com/browse/KOGITO-8129
> [KOGITO-8129] Async API guide

- serverlessworkflow/modules/ROOT/nav.adoc
- serverlessworkflow/modules/ROOT/pages/service-orchestration/orchestration-of-asyncapi-based-services.adoc
**JIRA:** [KOGITO-8129](https://issues.redhat.com/browse/KOGITO-8129)
followup to #288 
I also grouped the 2 OpenAPI guides together in the nav tab.
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a …
> KOGITO-8129 - Async API guide - fix

- serverlessworkflow/modules/ROOT/pages/cloud/build-and-deploy-with-serverless-operator-on-kubernetes.adoc
- serverlessworkflow/modules/ROOT/pages/service-orchestration/configuring-openapi-services-endpoints.adoc
Just a few typos I found while reading the docs.
<details>
<summary>
</summary>
Once the original pull request is …
> Fix operator typos + other minor fixes

- serverlessworkflow/antora.yml
- serverlessworkflow/modules/ROOT/pages/core/timeouts-support.adoc
**JIRA:**
<details>
<summary>
</summary> …
> [1.32.x] KOGITO-8653: Fix operator version in Kogito-Docs 1.32.x

- serverlessworkflow/modules/ROOT/nav.adoc
- serverlessworkflow/modules/ROOT/pages/cloud/knative-service-discovery.adoc
- serverlessworkflow/modules/ROOT/pages/cloud/kubernetes-service-discovery.adoc
- serverlessworkflow/modules/ROOT/pages/core/custom-functions-support.adoc
- serverlessworkflow/modules/ROOT/pages/index.adoc
- serverlessworkflow/modules/ROOT/pages/integrations/custom-functions-knative.adoc
**JIRA:** https://issues.redhat.com/browse/KOGITO-8414
This guide is for Knative custom function, which is implemented in https://github.com/kiegroup/kogito-runtimes/pull/2711
The example used by this guide is implemented in https://github.com/kiegroup/kogito-examples/pull/1526
**This PR should be merged only after the above PRs are merged.**
<details>
<summary>
</summary>
In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-7.67.x` to backport the original PR to the …
> KOGITO-8414 Added knative-service-discovery.adoc

- serverlessworkflow/modules/ROOT/pages/core/timeouts-support.adoc
**JIRA:**
<details>
<summary>
</summary> …
> KOGITO-8654: Fix syntax on timeout-support page

- serverlessworkflow/modules/ROOT/pages/index.adoc
**JIRA:** https://issues.redhat.com/browse/KOGITO-8401
**Description:** Brief introduction explaining the potential usage of Kogito SW in the cards.
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another …
> [KOGITO-8401] Add a brief introduction to Kogito SW capabilities in the home page

- serverlessworkflow/modules/ROOT/pages/release_notes.adoc
**JIRA:**
<details>
<summary>
</summary> …
> [1.34.x] Update release notes formatting

- serverlessworkflow/modules/ROOT/pages/core/configuration-properties.adoc
- serverlessworkflow/modules/ROOT/pages/persistence/persistence-with-postgresql.adoc
- serverlessworkflow/modules/ROOT/pages/persistence/postgresql-flyway-migration.adoc
**JIRA:** [KOGITO-8674](https://issues.redhat.com/browse/KOGITO-8674)
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change …
> KOGITO-8674: Update Postgresql schema migration guide for Flyway with JDBC addon

- CONTRIBUTING.md
A small update to the `contributing.md` file to be more verbose about the process and fix the JIRA query.
> Improvements in the contributing to RN section

- serverlessworkflow/modules/ROOT/pages/eventing/consume-producing-events-with-kafka.adoc
**JIRA:**
https://issues.redhat.com/browse/KOGITO-8676
> [KOGITO-8676] OnOverflow management

- serverlessworkflow/modules/ROOT/pages/core/custom-functions-support.adoc
**JIRA:**
https://issues.redhat.com/browse/KOGITO-8908
> [KOGITO-8908] Documenting sysout arguments and log level

- serverlessworkflow/antora.yml
A fix for [KOGITO-7783](https://issues.redhat.com/browse/KOGITO-7783) and #166.
<details>
<summary>
</summary>
Once the …
> KOGITO-7783 - Follow-up: Remove unused attributes

- .ci/jenkins/Jenkinsfile.setup-branch
This is the nightly responsibility
https://issues.redhat.com/browse/KOGITO-8981
Related:
- https://github.com/kiegroup/kogito-pipelines/pull/932
- https://github.com/kiegroup/kogito-runtimes/pull/2926
- https://github.com/kiegroup/kogito-apps/pull/1693
- https://github.com/kiegroup/kogito-examples/pull/1633
- https://github.com/kiegroup/kogito-images/pull/1487
- https://github.com/kiegroup/kogito-operator/pull/1453
- https://github.com/kiegroup/kogito-serverless-operator/pull/89
- https://github.com/kiegroup/kogito-docs/pull/327
> KOGITO-8981 Setup branch should not deploy

- serverlessworkflow/modules/ROOT/nav.adoc
- serverlessworkflow/modules/ROOT/pages/core/timeouts-support.adoc
- serverlessworkflow/modules/ROOT/pages/index.adoc
- serverlessworkflow/modules/ROOT/pages/persistence/postgresql-flyway-migration.adoc
- serverlessworkflow/modules/ROOT/pages/supporting-services/jobs-service.adoc
- serverlessworkflow/modules/ROOT/pages/use-cases/timeout-showcase-example.adoc
Minor fix for reference and moving the Job Service part to a new page under a new Supporting Services section.
**JIRA:**
<details>
<summary>
</summary> …
> [KOGITO-8820] Fix references in timeout guide and create a new section for job service

- serverlessworkflow/modules/ROOT/pages/release_notes.adoc
> Release Notes for 1.38.0

- serverlessworkflow/modules/ROOT/pages/cloud/quarkus/kubernetes-service-discovery.adoc
- serverlessworkflow/modules/ROOT/pages/integrations/custom-functions-knative.adoc
**JIRA:** https://issues.redhat.com/browse/KOGITO-9144
- https://github.com/kiegroup/kogito-runtimes/pull/2986
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release …
> KOGITO-9144 Added information about how to enable service discovery

- serverlessworkflow/antora.yml
- serverlessworkflow/modules/ROOT/pages/tooling/serverless-logic-web-tools/serverless-logic-web-tools-deploy-projects.adoc
- serverlessworkflow/modules/ROOT/pages/tooling/serverless-logic-web-tools/serverless-logic-web-tools-redhat-application-services-integration.adoc
**JIRA:** https://issues.redhat.com/browse/KOGITO-9057
**Description:** Removing content related to Streams for Apache Kafka since the tab was removed in https://github.com/kiegroup/kie-tools/pull/1583
- [NA] The nav.adoc file has a link to this guide in the proper category
- [NA] The index.adoc file has a card to this guide in the proper category, with a meaningful description
<details>
<summary>
</summary>
In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be backported to (e.g., `backport-7.67.x` to …
> KOGITO-9057 Remove Streams for Apache Kafka content from Serverless Logic Web Tools

- serverlessworkflow/modules/ROOT/pages/cloud/operator/known-issues.adoc
**JIRA:**
<details>
<summary>
</summary> …
> [KOGITO-9317] Update know-issues doc

- serverlessworkflow/modules/ROOT/pages/cloud/operator/developing-workflows.adoc
Small fixup for #355.
<details>
<summary>
</summary>
Once the original pull request is successfully merged, the …
> [Kogito-9243][KSW-GUIDE] Fixup

- CONTRIBUTING.md
- serverlessworkflow/modules/ROOT/pages/release_notes.adoc
Went through:
- https://github.com/kiegroup/kogito-runtimes/releases/tag/1.40.0.Final
- https://github.com/kiegroup/kogito-apps/releases/tag/1.40.0.Final
- https://github.com/kiegroup/kogito-examples/releases/tag/1.40.0.Final
> Update 1.40.0.Final release notes with core issues

- serverlessworkflow/modules/ROOT/pages/release_notes.adoc
**JIRA:**
<details>
<summary>
</summary> …
> Update cloud issues

- serverlessworkflow/modules/ROOT/pages/cloud/operator/build-and-deploy-workflows.adoc
- serverlessworkflow/modules/ROOT/pages/cloud/operator/configuring-workflows.adoc
- serverlessworkflow/modules/ROOT/pages/cloud/operator/developing-workflows.adoc
- serverlessworkflow/modules/ROOT/pages/cloud/operator/install-serverless-operator.adoc
- serverlessworkflow/modules/ROOT/pages/cloud/operator/known-issues.adoc
- serverlessworkflow/modules/ROOT/pages/cloud/operator/workflow-status-conditions.adoc
**JIRA:** https://issues.redhat.com/browse/KOGITO-9311
This PR provides some suggestions to improve the first-time user experience for the Kogito Serverless Operator documentation. 
I've approached this from the status of someone with no experience of the operator, trying to make things as clear as possible.
I've also tried to make sure we're being as consistent as possible across all of the docs.
<details>
<summary>
</summary>
In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull request must be …
> [KOGITO-9311] Suggested improvements for the Kogito Serverless Operator Documentation

- CONTRIBUTING.md
- serverlessworkflow/modules/ROOT/pages/release_notes.adoc
Release Notes for 1.40.0.Final
> [1.40.x] Release Notes for 1.40.0.Final

- serverlessworkflow/antora.yml
- serverlessworkflow/modules/ROOT/pages/cloud/common/_common_proc_deploy_kubectl_oc.adoc
- serverlessworkflow/modules/ROOT/pages/cloud/common/_prerequisites.adoc
- serverlessworkflow/modules/ROOT/pages/cloud/common/_proc_deploy_sw_kn_cli.adoc
- serverlessworkflow/modules/ROOT/pages/cloud/quarkus/deploying-on-minikube.adoc
- serverlessworkflow/modules/ROOT/pages/tooling/kn-plugin-workflow-overview.adoc
- serverlessworkflow/modules/ROOT/pages/tooling/quarkus-dev-ui-extension/quarkus-dev-ui-workflow-definition-page.adoc
**JIRA:**
<details>
<summary>
</summary> …
> some warning fixes

- serverlessworkflow/antora.yml
- serverlessworkflow/modules/ROOT/nav.adoc
- serverlessworkflow/modules/ROOT/pages/cloud/index.adoc
- serverlessworkflow/modules/ROOT/pages/cloud/operator/build-and-deploy-workflows.adoc
- serverlessworkflow/modules/ROOT/pages/cloud/operator/configuring-workflows.adoc
- serverlessworkflow/modules/ROOT/pages/cloud/operator/developing-workflows.adoc
- serverlessworkflow/modules/ROOT/pages/cloud/operator/install-serverless-operator.adoc
- serverlessworkflow/modules/ROOT/pages/cloud/operator/known-issues.adoc
- serverlessworkflow/modules/ROOT/pages/cloud/operator/referencing-resource-files.adoc
- serverlessworkflow/modules/ROOT/pages/cloud/operator/workflow-status-conditions.adoc
- serverlessworkflow/modules/ROOT/pages/cloud/quarkus/kubernetes-service-discovery.adoc
**JIRA:** https://issues.redhat.com/browse/KOGITO-9464
**Description:** In this PR, we add a few new guides for the operator use cases and update the old ones.
TODO:
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring …
> [KOGITO-9464] Update Operator Guides and Use Cases

- serverlessworkflow/modules/ROOT/pages/core/defining-an-input-schema-for-workflows.adoc
**JIRA:**
https://issues.redhat.com/browse/KOGITO-9468
> [KOGITO-9468] Describing Output schema

- CONTRIBUTING.md
- serverlessworkflow/modules/ROOT/pages/release_notes.adoc
I did the same as @radtriste in #372.
<details>
<summary>
</summary>
Once the original pull request is successfully …
> Update 1.41.0.Final release notes with core issues

- serverlessworkflow/modules/ROOT/pages/cloud/operator/build-and-deploy-workflows.adoc
- serverlessworkflow/modules/ROOT/pages/cloud/operator/configuring-workflows.adoc
- serverlessworkflow/modules/ROOT/pages/cloud/operator/developing-workflows.adoc
- serverlessworkflow/modules/ROOT/pages/cloud/operator/install-serverless-operator.adoc
- serverlessworkflow/modules/ROOT/pages/cloud/operator/known-issues.adoc
- serverlessworkflow/modules/ROOT/pages/cloud/operator/referencing-resource-files.adoc
+ fix small doc command
**JIRA:**
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them …
> Updating operator tags

- serverlessworkflow/modules/ROOT/pages/release_notes.adoc
**JIRA:**
<details>
<summary>
</summary> …
> [1.41.x] Update release_notes.adoc

- serverlessworkflow/modules/ROOT/pages/release_notes.adoc
> Release Notes for 1.42.0.Final Version

- serverlessworkflow/modules/ROOT/pages/core/custom-functions-support.adoc
**JIRA:** https://issues.redhat.com/browse/KOGITO-9158
This PR depends on: https://github.com/kiegroup/kogito-runtimes/pull/2993
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release …
> KOGITO-9158 Changed Knative function Request Timeout configuration name 

- serverlessworkflow/antora.yml
**JIRA:** [KOGITO-9668](https://issues.redhat.com/browse/KOGITO-9668)
**Description:** To fix an issue with tab openings in VS Code, we had to upgrade the minimal version required to use our extensions.
<details>
<summary>
</summary> …
> KOGITO-9668: SWF Editor - In VSCode the diagram reloads if a user clicks on any area of the canvas

- .github/workflows/jenkins-tests-PR.yml
**JIRA:**
<details>
<summary>
</summary> …
> Fix DSL check

- antora-playbook-author.yml
- antora-playbook.yml
- serverlessworkflow/antora.yml
- serverlessworkflow/modules/ROOT/pages/cloud/operator/install-serverless-operator.adoc
- serverlessworkflow/modules/ROOT/pages/cloud/operator/known-issues.adoc
**JIRA:** https://issues.redhat.com/browse/KOGITO-9683
Small update to the Operator Installation Guide to point users to OLM/OperatorHub's way of installing. The old installation method now is only for "local/manual" use cases, as highlighted in the document.
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to …
> [KOGITO-9683] - Update Operator's installation guide to reflect OLM

- serverlessworkflow/antora.yml
I made a mistake while merging the cherry-picks.
> Fix version rc

- serverlessworkflow/modules/ROOT/pages/release_notes.adoc
Release notes for SonataFlow 1.43.0
> Release notes for SonataFlow 1.43.0

- serverlessworkflow/modules/ROOT/pages/testing-and-troubleshooting/kn-plugin-workflow-overview.adoc
[KOGITO-9460](https://issues.redhat.com/browse/KOGITO-9460)
**Description:** Improve KN CLI Workflow plugin guide.
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it …
> KOGITO-9460: Create a new guide describing the workflow CLI

- serverlessworkflow/modules/ROOT/pages/testing-and-troubleshooting/kn-plugin-workflow-overview.adoc
**JIRA:** [KOGITO-9460](https://issues.redhat.com/browse/KOGITO-9460)
Fixes for `main` which were already done on the backports of #432.
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific …
> Fix the workflow CLI doc

- .github/CODEOWNERS
**JIRA:**
<details>
<summary>
</summary> …
> Remove `@radtriste` from code owners

- serverlessworkflow/modules/ROOT/pages/release_notes.adoc
Short PR to update the Release Notes for 1.44.0 version.
> Release Notes for 1.44.0 version

- serverlessworkflow/modules/ROOT/pages/cloud/operator/build-and-deploy-workflows.adoc
https://issues.redhat.com/browse/KOGITO-9800
Update the doc from the PR review for:
https://github.com/flows-examples/techpreview2/pull/3
- [ X] You have read the [contributions doc](https://github.com/kiegroup/kogito-docs/blob/main/CONTRIBUTING.md)
- [ X] Pull Request title is properly formatted: `KOGITO-XYZ Subject`
- [ X] Pull Request title contains the target branch if not targeting main: `[0.9.x] KOGITO-XYZ Subject`
- [X ] The nav.adoc file has a link to this guide in the proper category
- [ X] The index.adoc file has a card to this guide in the proper category, with a meaningful description
<details>
<summary>
</summary>
In order to automatically create a …
> [KOGITO-9800] Add minikube registry addon

- serverlessworkflow/antora.yml
- serverlessworkflow/modules/ROOT/pages/getting-started/create-your-first-workflow-service.adoc
**JIRA:** https://issues.redhat.com/browse/KOGITO-8874
**Description:** 
- Use `kn workflow quarkus` commands in the docs. This is used in the `kn-workflow` for quite a time. 
- Update version of `kn workflow` recommended by the docs.
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a …
> KOGITO-8874 Update documentation to use `kn-workflow quarkus`

- serverlessworkflow/modules/ROOT/pages/cloud/index.adoc
This is a small PR to verify if the changes in the DNS took effect. Since we can't manually run GHA pages publishing, we need a change in build site.
Follow the tracking here: https://issues.apache.org/jira/browse/INFRA-25091
> [INFRA-25091] Small change to test GH Pages trigger

- serverlessworkflow/modules/ROOT/pages/cloud/index.adoc
This is a small PR to verify if the changes in the settings took effect. Since we can't manually run GHA page publishing, we need a change in the build site.
Follow the tracking here: https://issues.apache.org/jira/browse/INFRA-25091
**JIRA:**
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change …
> [INFRA-25091] Small grammar fix in cloud index page

- .asf.yaml
**JIRA:**
<details>
<summary>
</summary> …
> Update .asf.yaml to enable GitHub Issues

- .ci/jenkins/Jenkinsfile.post-release
- .ci/jenkins/Jenkinsfile.setup-branch
- .ci/jenkins/dsl/jobs.groovy
Fixes:
* apache/incubator-kie-issues#767
Ensemble:
* apache/incubator-kie-kogito-pipelines#1146
* apache/incubator-kie-kogito-runtimes#3331
* apache/incubator-kie-kogito-apps#1937
* apache/incubator-kie-kogito-examples#1844
* apache/incubator-kie-kogito-images#1717
* apache/incubator-kie-kogito-docs#524
* apache/incubator-kie-docs#4534
* apache/incubator-kie-drools#5624
* apache/incubator-kie-benchmarks#278
* apache/incubator-kie-optaplanner#3045
* apache/incubator-kie-optaplanner-quickstarts#621
* apache/incubator-kie-optaplanner-quickstarts#622
> kie-issues#767: set user config for git

- serverlessworkflow/modules/ROOT/pages/cloud/operator/build-and-deploy-workflows.adoc
**JIRA:**
https://issues.redhat.com/browse/KOGITO-8792
Relates to https://github.com/apache/incubator-kie-kogito-serverless-operator/pull/318
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a …
> [KOGITO-8792] Add the restart build notes to the build guide

- serverlessworkflow/modules/ROOT/nav.adoc
- serverlessworkflow/modules/ROOT/pages/cloud/index.adoc
- serverlessworkflow/modules/ROOT/pages/cloud/operator/build-and-deploy-workflows.adoc
- serverlessworkflow/modules/ROOT/pages/cloud/operator/supporting-services.adoc
**JIRA:**
https://issues.redhat.com/browse/KOGITO-9923
Explains how to use the new Data Index service deployment feature
https://github.com/apache/incubator-kie-kogito-serverless-operator/pull/287
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main …
> KOGITO-9923 Data Index service deployment

- .ci/jenkins/Jenkinsfile.post-release
- .ci/jenkins/Jenkinsfile.setup-branch
part of https://github.com/apache/incubator-kie-issues/issues/777
> kie-issues#777: Allow restricting jenkins agent labels for pipelines

- .github/workflows/pr-preview-publish.yml
Quick fix for the GH attribute.
> Fix github-token attribute in preview workflow

- serverlessworkflow/modules/ROOT/pages/getting-started/create-your-first-workflow-service-with-kn-cli-and-vscode.adoc
- serverlessworkflow/modules/ROOT/pages/getting-started/java-embedded-workflows.adoc
- serverlessworkflow/modules/ROOT/pages/getting-started/learning-environment.adoc
- serverlessworkflow/modules/ROOT/pages/getting-started/preparing-environment.adoc
- serverlessworkflow/modules/ROOT/pages/getting-started/production-environment.adoc
Fixes minor typos in the Getting started guides
> NO-ISSUE: Fix minor typos in getting started guides

- serverlessworkflow/antora.yml
- serverlessworkflow/modules/ROOT/nav.adoc
- serverlessworkflow/modules/ROOT/pages/cloud/index.adoc
- serverlessworkflow/modules/ROOT/pages/cloud/operator/build-and-deploy-workflows.adoc
- serverlessworkflow/modules/ROOT/pages/cloud/operator/building-custom-images.adoc
- serverlessworkflow/modules/ROOT/pages/cloud/operator/global-configuration.adoc
Closes #560 
Closes #548
Introduces the documentation for the feature:
- https://github.com/apache/incubator-kie-kogito-serverless-operator/pull/416
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring …
> Issue #560 - Introduce Global Configuration for Operator section

- package-lock.json
- package.json
Closes/Fixes/Resolves #619 
Bumping the `asciidoctor-emoji` version to 0.5.0 fixes the loading emoji issue.
> Issues-619 Bump asciidoctor-emoji version to 0.5.0

- serverlessworkflow/modules/ROOT/pages/use-cases/advanced-developer-use-cases/persistence/postgresql-flyway-migration.adoc
Closes #637 
<details>
<summary>
</summary> …
> issue-637: update kogito_ddl_script_url to repository.apache.org

- serverlessworkflow/modules/ROOT/pages/use-cases/advanced-developer-use-cases/data-index/data-index-usecase-singleton.adoc
Fixing include adding the missing ':'
> Fixing include in data-index-usecase-singleton.adoc

- antora-playbook.yml
Fixes faling gh-pages pushes on main.
> NO_ISSUE: Fix antora-playbook.yml latest_version_segment

- serverlessworkflow/antora.yml
- serverlessworkflow/modules/ROOT/nav.adoc
- serverlessworkflow/modules/ROOT/pages/_common-content/getting-started-requirement.adoc
- serverlessworkflow/modules/ROOT/pages/cloud/operator/install-serverless-operator.adoc
- serverlessworkflow/modules/ROOT/pages/core/cncf-serverless-workflow-specification-support.adoc
- serverlessworkflow/modules/ROOT/pages/core/understanding-workflow-error-handling.adoc
- serverlessworkflow/modules/ROOT/pages/core/working-with-callbacks.adoc
- serverlessworkflow/modules/ROOT/pages/core/working-with-parallelism.adoc
- serverlessworkflow/modules/ROOT/pages/getting-started/introduction-sonataflow-development-guide.adoc
- serverlessworkflow/modules/ROOT/pages/getting-started/preparing-environment.adoc
- serverlessworkflow/modules/ROOT/pages/index.adoc
- serverlessworkflow/modules/ROOT/pages/service-orchestration/orchestration-of-openapi-based-services.adoc
- serverlessworkflow/modules/ROOT/pages/testing-and-troubleshooting/kn-plugin-workflow-overview.adoc
Closes/Fixes/Resolves #695 
Follow up PR for  #695
Also reorganizes the sections a bit.
> kie-kogito-docs#695: Holistic review follow-up

- serverlessworkflow/antora.yml
- serverlessworkflow/modules/ROOT/pages/cloud/operator/build-and-deploy-workflows.adoc
Bring docs up to date for 10.0.0 version
Related PR #700
> [10.0.x] NO_ISSUE: Update versions to 10.0.0

- serverlessworkflow/antora.yml
- serverlessworkflow/modules/ROOT/pages/cloud/operator/build-and-deploy-workflows.adoc
> [10.0.x] Update versions to 10.0.0

- antora-playbook.yml
> NO_ISSUE: Update antora-playbook.yml to include 10.0.x branch

- serverlessworkflow/modules/ROOT/pages/core/cncf-serverless-workflow-specification-support.adoc
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them …
> Async API and sleep are implemented

- antora-playbook.yml
Use only 10.0.x when built from this branch
> [10.0.x] Update playbook for 10.0.x

- serverlessworkflow/antora.yml
Fixes wrong URL.
Thanks @pibizza
> NO_ISSUE: Fix location of operator to kie-tools

- serverlessworkflow/antora.yml
- serverlessworkflow/modules/ROOT/pages/cloud/operator/install-serverless-operator.adoc
Backports #706 and #707 to 10.0.x
> [10.0.x] Backport:  Fix manual operator install guide

- serverlessworkflow/modules/ROOT/pages/cloud/operator/supporting-services.adoc
Closes/Fixes/Resolves #716 
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch (usually the main one) to another one, which is generally referring to a still maintained release branch. Keeping it simple: it is about to move a specific change or a set of them from one …
> kie-kogito-docs-716: [sonataflow-operator] Improvements on the DB migration documentation section

- serverlessworkflow/antora.yml
Implement kogito_branch with value main.
Removes 2 old links.
> NO_ISSUE: Implement kogito_branch variable

- serverlessworkflow/modules/ROOT/nav.adoc
- serverlessworkflow/modules/ROOT/pages/cloud/operator/config-maven-quarkus.adoc
Fixes https://github.com/apache/incubator-kie-tools/issues/3124
In this PR, we include the documentation for https://github.com/apache/incubator-kie-tools/pull/3127 PR.
The `Maven Configuration` guide has been moved to `Cloud -> Operator -> Deployment Profiles` section. Within this guide, we added a new section describing how to configure the Quarkus Registry.
- https://github.com/apache/incubator-kie-tools/pull/3127
<details>
<summary>
</summary>
In order to automatically create a **backporting pull request** please add one or more labels having the following format `backport-<branch-name>`, where `<branch-name>` is the name of the branch where the pull …
> Fix #kie-tools-3124 - Adding documentation about Quarkus Registry

- serverlessworkflow/modules/ROOT/assets/images/security/token-exchange-sequence.svg
- serverlessworkflow/modules/ROOT/nav.adoc
- serverlessworkflow/modules/ROOT/pages/index.adoc
- serverlessworkflow/modules/ROOT/pages/security/token-exchange-for-openapi-services.adoc
Fix apache/incubator-kie-issues#1900
Add doc for token exchange feature
* https://github.com/apache/incubator-kie-kogito-runtimes/pull/4000
* https://github.com/apache/incubator-kie-kogito-runtimes/pull/3928
*
<details>
<summary>
</summary>
> **NOTE**: **backporting** is an action aiming to move a change (usually a commit) from a branch …
> [Fix apache/incubator-kie-issues#1900] Add doc for token exchange
